// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package azureextensionmodule.proxies;

public class _links_2
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject _links_2MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AzureExtensionModule._links_2";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_links_2_System_ChangedBy("AzureExtensionModule._links_2_System_ChangedBy"),
		Avatar_2__links_2("AzureExtensionModule.Avatar_2__links_2"),
		_links_2_Resource_4("AzureExtensionModule._links_2_Resource_4"),
		Self__links_2("AzureExtensionModule.Self__links_2"),
		WorkItemUpdates__links_2("AzureExtensionModule.WorkItemUpdates__links_2"),
		Parent__links_2("AzureExtensionModule.Parent__links_2"),
		Html__links_2("AzureExtensionModule.Html__links_2"),
		_links_2_Resource_6("AzureExtensionModule._links_2_Resource_6");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public _links_2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected _links_2(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject _links_2MendixObject)
	{
		if (_links_2MendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, _links_2MendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this._links_2MendixObject = _links_2MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use '_links_2.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static azureextensionmodule.proxies._links_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return azureextensionmodule.proxies._links_2.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static azureextensionmodule.proxies._links_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new azureextensionmodule.proxies._links_2(context, mendixObject);
	}

	public static azureextensionmodule.proxies._links_2 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return azureextensionmodule.proxies._links_2.initialize(context, mendixObject);
	}

	public static java.util.List<azureextensionmodule.proxies._links_2> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> azureextensionmodule.proxies._links_2.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of _links_2_System_ChangedBy
	 */
	public final azureextensionmodule.proxies.System_ChangedBy get_links_2_System_ChangedBy() throws com.mendix.core.CoreException
	{
		return get_links_2_System_ChangedBy(getContext());
	}

	/**
	 * @param context
	 * @return value of _links_2_System_ChangedBy
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.System_ChangedBy get_links_2_System_ChangedBy(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.System_ChangedBy result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames._links_2_System_ChangedBy.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.System_ChangedBy.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of _links_2_System_ChangedBy
	 * @param _links_2_system_changedby
	 */
	public final void set_links_2_System_ChangedBy(azureextensionmodule.proxies.System_ChangedBy _links_2_system_changedby)
	{
		set_links_2_System_ChangedBy(getContext(), _links_2_system_changedby);
	}

	/**
	 * Set value of _links_2_System_ChangedBy
	 * @param context
	 * @param _links_2_system_changedby
	 */
	public final void set_links_2_System_ChangedBy(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.System_ChangedBy _links_2_system_changedby)
	{
		if (_links_2_system_changedby == null) {
			getMendixObject().setValue(context, MemberNames._links_2_System_ChangedBy.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames._links_2_System_ChangedBy.toString(), _links_2_system_changedby.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Avatar_2__links_2
	 */
	public final azureextensionmodule.proxies.Avatar_2 getAvatar_2__links_2() throws com.mendix.core.CoreException
	{
		return getAvatar_2__links_2(getContext());
	}

	/**
	 * @param context
	 * @return value of Avatar_2__links_2
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Avatar_2 getAvatar_2__links_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Avatar_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Avatar_2__links_2.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Avatar_2.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Avatar_2__links_2
	 * @param avatar_2__links_2
	 */
	public final void setAvatar_2__links_2(azureextensionmodule.proxies.Avatar_2 avatar_2__links_2)
	{
		setAvatar_2__links_2(getContext(), avatar_2__links_2);
	}

	/**
	 * Set value of Avatar_2__links_2
	 * @param context
	 * @param avatar_2__links_2
	 */
	public final void setAvatar_2__links_2(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Avatar_2 avatar_2__links_2)
	{
		if (avatar_2__links_2 == null) {
			getMendixObject().setValue(context, MemberNames.Avatar_2__links_2.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Avatar_2__links_2.toString(), avatar_2__links_2.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of _links_2_Resource_4
	 */
	public final azureextensionmodule.proxies.Resource_4 get_links_2_Resource_4() throws com.mendix.core.CoreException
	{
		return get_links_2_Resource_4(getContext());
	}

	/**
	 * @param context
	 * @return value of _links_2_Resource_4
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Resource_4 get_links_2_Resource_4(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Resource_4 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames._links_2_Resource_4.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Resource_4.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of _links_2_Resource_4
	 * @param _links_2_resource_4
	 */
	public final void set_links_2_Resource_4(azureextensionmodule.proxies.Resource_4 _links_2_resource_4)
	{
		set_links_2_Resource_4(getContext(), _links_2_resource_4);
	}

	/**
	 * Set value of _links_2_Resource_4
	 * @param context
	 * @param _links_2_resource_4
	 */
	public final void set_links_2_Resource_4(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Resource_4 _links_2_resource_4)
	{
		if (_links_2_resource_4 == null) {
			getMendixObject().setValue(context, MemberNames._links_2_Resource_4.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames._links_2_Resource_4.toString(), _links_2_resource_4.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Self__links_2
	 */
	public final azureextensionmodule.proxies.Self getSelf__links_2() throws com.mendix.core.CoreException
	{
		return getSelf__links_2(getContext());
	}

	/**
	 * @param context
	 * @return value of Self__links_2
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Self getSelf__links_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Self result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Self__links_2.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Self.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Self__links_2
	 * @param self__links_2
	 */
	public final void setSelf__links_2(azureextensionmodule.proxies.Self self__links_2)
	{
		setSelf__links_2(getContext(), self__links_2);
	}

	/**
	 * Set value of Self__links_2
	 * @param context
	 * @param self__links_2
	 */
	public final void setSelf__links_2(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Self self__links_2)
	{
		if (self__links_2 == null) {
			getMendixObject().setValue(context, MemberNames.Self__links_2.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Self__links_2.toString(), self__links_2.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkItemUpdates__links_2
	 */
	public final azureextensionmodule.proxies.WorkItemUpdates getWorkItemUpdates__links_2() throws com.mendix.core.CoreException
	{
		return getWorkItemUpdates__links_2(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkItemUpdates__links_2
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.WorkItemUpdates getWorkItemUpdates__links_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.WorkItemUpdates result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkItemUpdates__links_2.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.WorkItemUpdates.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkItemUpdates__links_2
	 * @param workitemupdates__links_2
	 */
	public final void setWorkItemUpdates__links_2(azureextensionmodule.proxies.WorkItemUpdates workitemupdates__links_2)
	{
		setWorkItemUpdates__links_2(getContext(), workitemupdates__links_2);
	}

	/**
	 * Set value of WorkItemUpdates__links_2
	 * @param context
	 * @param workitemupdates__links_2
	 */
	public final void setWorkItemUpdates__links_2(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.WorkItemUpdates workitemupdates__links_2)
	{
		if (workitemupdates__links_2 == null) {
			getMendixObject().setValue(context, MemberNames.WorkItemUpdates__links_2.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkItemUpdates__links_2.toString(), workitemupdates__links_2.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parent__links_2
	 */
	public final azureextensionmodule.proxies.Parent getParent__links_2() throws com.mendix.core.CoreException
	{
		return getParent__links_2(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent__links_2
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Parent getParent__links_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Parent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent__links_2.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Parent.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parent__links_2
	 * @param parent__links_2
	 */
	public final void setParent__links_2(azureextensionmodule.proxies.Parent parent__links_2)
	{
		setParent__links_2(getContext(), parent__links_2);
	}

	/**
	 * Set value of Parent__links_2
	 * @param context
	 * @param parent__links_2
	 */
	public final void setParent__links_2(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Parent parent__links_2)
	{
		if (parent__links_2 == null) {
			getMendixObject().setValue(context, MemberNames.Parent__links_2.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parent__links_2.toString(), parent__links_2.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Html__links_2
	 */
	public final azureextensionmodule.proxies.Html getHtml__links_2() throws com.mendix.core.CoreException
	{
		return getHtml__links_2(getContext());
	}

	/**
	 * @param context
	 * @return value of Html__links_2
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Html getHtml__links_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Html result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Html__links_2.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Html.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Html__links_2
	 * @param html__links_2
	 */
	public final void setHtml__links_2(azureextensionmodule.proxies.Html html__links_2)
	{
		setHtml__links_2(getContext(), html__links_2);
	}

	/**
	 * Set value of Html__links_2
	 * @param context
	 * @param html__links_2
	 */
	public final void setHtml__links_2(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Html html__links_2)
	{
		if (html__links_2 == null) {
			getMendixObject().setValue(context, MemberNames.Html__links_2.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Html__links_2.toString(), html__links_2.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of _links_2_Resource_6
	 */
	public final azureextensionmodule.proxies.Resource_6 get_links_2_Resource_6() throws com.mendix.core.CoreException
	{
		return get_links_2_Resource_6(getContext());
	}

	/**
	 * @param context
	 * @return value of _links_2_Resource_6
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Resource_6 get_links_2_Resource_6(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Resource_6 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames._links_2_Resource_6.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Resource_6.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of _links_2_Resource_6
	 * @param _links_2_resource_6
	 */
	public final void set_links_2_Resource_6(azureextensionmodule.proxies.Resource_6 _links_2_resource_6)
	{
		set_links_2_Resource_6(getContext(), _links_2_resource_6);
	}

	/**
	 * Set value of _links_2_Resource_6
	 * @param context
	 * @param _links_2_resource_6
	 */
	public final void set_links_2_Resource_6(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Resource_6 _links_2_resource_6)
	{
		if (_links_2_resource_6 == null) {
			getMendixObject().setValue(context, MemberNames._links_2_Resource_6.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames._links_2_Resource_6.toString(), _links_2_resource_6.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return _links_2MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final azureextensionmodule.proxies._links_2 that = (azureextensionmodule.proxies._links_2) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
