// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package azureextensionmodule.proxies;

public class Custom_NPItype
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject custom_NPItypeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AzureExtensionModule.Custom_NPItype";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NewValue("NewValue"),
		Custom_NPItype_Fields_7("AzureExtensionModule.Custom_NPItype_Fields_7"),
		Custom_NPItype_Fields_8("AzureExtensionModule.Custom_NPItype_Fields_8");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Custom_NPItype(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Custom_NPItype(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject custom_NPItypeMendixObject)
	{
		if (custom_NPItypeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, custom_NPItypeMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.custom_NPItypeMendixObject = custom_NPItypeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Custom_NPItype.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static azureextensionmodule.proxies.Custom_NPItype initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return azureextensionmodule.proxies.Custom_NPItype.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static azureextensionmodule.proxies.Custom_NPItype initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new azureextensionmodule.proxies.Custom_NPItype(context, mendixObject);
	}

	public static azureextensionmodule.proxies.Custom_NPItype load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return azureextensionmodule.proxies.Custom_NPItype.initialize(context, mendixObject);
	}

	public static java.util.List<azureextensionmodule.proxies.Custom_NPItype> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> azureextensionmodule.proxies.Custom_NPItype.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NewValue
	 */
	public final java.lang.String getNewValue()
	{
		return getNewValue(getContext());
	}

	/**
	 * @param context
	 * @return value of NewValue
	 */
	public final java.lang.String getNewValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NewValue.toString());
	}

	/**
	 * Set value of NewValue
	 * @param newvalue
	 */
	public final void setNewValue(java.lang.String newvalue)
	{
		setNewValue(getContext(), newvalue);
	}

	/**
	 * Set value of NewValue
	 * @param context
	 * @param newvalue
	 */
	public final void setNewValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String newvalue)
	{
		getMendixObject().setValue(context, MemberNames.NewValue.toString(), newvalue);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Custom_NPItype_Fields_7
	 */
	public final azureextensionmodule.proxies.Fields_7 getCustom_NPItype_Fields_7() throws com.mendix.core.CoreException
	{
		return getCustom_NPItype_Fields_7(getContext());
	}

	/**
	 * @param context
	 * @return value of Custom_NPItype_Fields_7
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Fields_7 getCustom_NPItype_Fields_7(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Fields_7 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Custom_NPItype_Fields_7.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Fields_7.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Custom_NPItype_Fields_7
	 * @param custom_npitype_fields_7
	 */
	public final void setCustom_NPItype_Fields_7(azureextensionmodule.proxies.Fields_7 custom_npitype_fields_7)
	{
		setCustom_NPItype_Fields_7(getContext(), custom_npitype_fields_7);
	}

	/**
	 * Set value of Custom_NPItype_Fields_7
	 * @param context
	 * @param custom_npitype_fields_7
	 */
	public final void setCustom_NPItype_Fields_7(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Fields_7 custom_npitype_fields_7)
	{
		if (custom_npitype_fields_7 == null) {
			getMendixObject().setValue(context, MemberNames.Custom_NPItype_Fields_7.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Custom_NPItype_Fields_7.toString(), custom_npitype_fields_7.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Custom_NPItype_Fields_8
	 */
	public final azureextensionmodule.proxies.Fields_8 getCustom_NPItype_Fields_8() throws com.mendix.core.CoreException
	{
		return getCustom_NPItype_Fields_8(getContext());
	}

	/**
	 * @param context
	 * @return value of Custom_NPItype_Fields_8
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Fields_8 getCustom_NPItype_Fields_8(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Fields_8 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Custom_NPItype_Fields_8.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Fields_8.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Custom_NPItype_Fields_8
	 * @param custom_npitype_fields_8
	 */
	public final void setCustom_NPItype_Fields_8(azureextensionmodule.proxies.Fields_8 custom_npitype_fields_8)
	{
		setCustom_NPItype_Fields_8(getContext(), custom_npitype_fields_8);
	}

	/**
	 * Set value of Custom_NPItype_Fields_8
	 * @param context
	 * @param custom_npitype_fields_8
	 */
	public final void setCustom_NPItype_Fields_8(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Fields_8 custom_npitype_fields_8)
	{
		if (custom_npitype_fields_8 == null) {
			getMendixObject().setValue(context, MemberNames.Custom_NPItype_Fields_8.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Custom_NPItype_Fields_8.toString(), custom_npitype_fields_8.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return custom_NPItypeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final azureextensionmodule.proxies.Custom_NPItype that = (azureextensionmodule.proxies.Custom_NPItype) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
