// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package azureextensionmodule.proxies;

public class Fields_6
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject fields_6MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AzureExtensionModule.Fields_6";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Fields_6_Resource_4("AzureExtensionModule.Fields_6_Resource_4"),
		System_Rev_Fields_6("AzureExtensionModule.System_Rev_Fields_6"),
		System_AuthorizedDate_Fields_6("AzureExtensionModule.System_AuthorizedDate_Fields_6"),
		System_RevisedDate_Fields_6("AzureExtensionModule.System_RevisedDate_Fields_6"),
		System_ChangedDate_Fields_6("AzureExtensionModule.System_ChangedDate_Fields_6"),
		System_Watermark_Fields_6("AzureExtensionModule.System_Watermark_Fields_6"),
		System_Title_Fields_6("AzureExtensionModule.System_Title_Fields_6");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Fields_6(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Fields_6(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fields_6MendixObject)
	{
		if (fields_6MendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, fields_6MendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.fields_6MendixObject = fields_6MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Fields_6.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static azureextensionmodule.proxies.Fields_6 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return azureextensionmodule.proxies.Fields_6.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static azureextensionmodule.proxies.Fields_6 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new azureextensionmodule.proxies.Fields_6(context, mendixObject);
	}

	public static azureextensionmodule.proxies.Fields_6 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return azureextensionmodule.proxies.Fields_6.initialize(context, mendixObject);
	}

	public static java.util.List<azureextensionmodule.proxies.Fields_6> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> azureextensionmodule.proxies.Fields_6.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Fields_6_Resource_4
	 */
	public final azureextensionmodule.proxies.Resource_4 getFields_6_Resource_4() throws com.mendix.core.CoreException
	{
		return getFields_6_Resource_4(getContext());
	}

	/**
	 * @param context
	 * @return value of Fields_6_Resource_4
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Resource_4 getFields_6_Resource_4(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Resource_4 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Fields_6_Resource_4.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Resource_4.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Fields_6_Resource_4
	 * @param fields_6_resource_4
	 */
	public final void setFields_6_Resource_4(azureextensionmodule.proxies.Resource_4 fields_6_resource_4)
	{
		setFields_6_Resource_4(getContext(), fields_6_resource_4);
	}

	/**
	 * Set value of Fields_6_Resource_4
	 * @param context
	 * @param fields_6_resource_4
	 */
	public final void setFields_6_Resource_4(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Resource_4 fields_6_resource_4)
	{
		if (fields_6_resource_4 == null) {
			getMendixObject().setValue(context, MemberNames.Fields_6_Resource_4.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Fields_6_Resource_4.toString(), fields_6_resource_4.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of System_Rev_Fields_6
	 */
	public final azureextensionmodule.proxies.System_Rev getSystem_Rev_Fields_6() throws com.mendix.core.CoreException
	{
		return getSystem_Rev_Fields_6(getContext());
	}

	/**
	 * @param context
	 * @return value of System_Rev_Fields_6
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.System_Rev getSystem_Rev_Fields_6(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.System_Rev result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.System_Rev_Fields_6.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.System_Rev.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of System_Rev_Fields_6
	 * @param system_rev_fields_6
	 */
	public final void setSystem_Rev_Fields_6(azureextensionmodule.proxies.System_Rev system_rev_fields_6)
	{
		setSystem_Rev_Fields_6(getContext(), system_rev_fields_6);
	}

	/**
	 * Set value of System_Rev_Fields_6
	 * @param context
	 * @param system_rev_fields_6
	 */
	public final void setSystem_Rev_Fields_6(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.System_Rev system_rev_fields_6)
	{
		if (system_rev_fields_6 == null) {
			getMendixObject().setValue(context, MemberNames.System_Rev_Fields_6.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.System_Rev_Fields_6.toString(), system_rev_fields_6.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of System_AuthorizedDate_Fields_6
	 */
	public final azureextensionmodule.proxies.System_AuthorizedDate getSystem_AuthorizedDate_Fields_6() throws com.mendix.core.CoreException
	{
		return getSystem_AuthorizedDate_Fields_6(getContext());
	}

	/**
	 * @param context
	 * @return value of System_AuthorizedDate_Fields_6
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.System_AuthorizedDate getSystem_AuthorizedDate_Fields_6(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.System_AuthorizedDate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.System_AuthorizedDate_Fields_6.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.System_AuthorizedDate.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of System_AuthorizedDate_Fields_6
	 * @param system_authorizeddate_fields_6
	 */
	public final void setSystem_AuthorizedDate_Fields_6(azureextensionmodule.proxies.System_AuthorizedDate system_authorizeddate_fields_6)
	{
		setSystem_AuthorizedDate_Fields_6(getContext(), system_authorizeddate_fields_6);
	}

	/**
	 * Set value of System_AuthorizedDate_Fields_6
	 * @param context
	 * @param system_authorizeddate_fields_6
	 */
	public final void setSystem_AuthorizedDate_Fields_6(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.System_AuthorizedDate system_authorizeddate_fields_6)
	{
		if (system_authorizeddate_fields_6 == null) {
			getMendixObject().setValue(context, MemberNames.System_AuthorizedDate_Fields_6.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.System_AuthorizedDate_Fields_6.toString(), system_authorizeddate_fields_6.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of System_RevisedDate_Fields_6
	 */
	public final azureextensionmodule.proxies.System_RevisedDate getSystem_RevisedDate_Fields_6() throws com.mendix.core.CoreException
	{
		return getSystem_RevisedDate_Fields_6(getContext());
	}

	/**
	 * @param context
	 * @return value of System_RevisedDate_Fields_6
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.System_RevisedDate getSystem_RevisedDate_Fields_6(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.System_RevisedDate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.System_RevisedDate_Fields_6.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.System_RevisedDate.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of System_RevisedDate_Fields_6
	 * @param system_reviseddate_fields_6
	 */
	public final void setSystem_RevisedDate_Fields_6(azureextensionmodule.proxies.System_RevisedDate system_reviseddate_fields_6)
	{
		setSystem_RevisedDate_Fields_6(getContext(), system_reviseddate_fields_6);
	}

	/**
	 * Set value of System_RevisedDate_Fields_6
	 * @param context
	 * @param system_reviseddate_fields_6
	 */
	public final void setSystem_RevisedDate_Fields_6(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.System_RevisedDate system_reviseddate_fields_6)
	{
		if (system_reviseddate_fields_6 == null) {
			getMendixObject().setValue(context, MemberNames.System_RevisedDate_Fields_6.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.System_RevisedDate_Fields_6.toString(), system_reviseddate_fields_6.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of System_ChangedDate_Fields_6
	 */
	public final azureextensionmodule.proxies.System_ChangedDate getSystem_ChangedDate_Fields_6() throws com.mendix.core.CoreException
	{
		return getSystem_ChangedDate_Fields_6(getContext());
	}

	/**
	 * @param context
	 * @return value of System_ChangedDate_Fields_6
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.System_ChangedDate getSystem_ChangedDate_Fields_6(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.System_ChangedDate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.System_ChangedDate_Fields_6.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.System_ChangedDate.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of System_ChangedDate_Fields_6
	 * @param system_changeddate_fields_6
	 */
	public final void setSystem_ChangedDate_Fields_6(azureextensionmodule.proxies.System_ChangedDate system_changeddate_fields_6)
	{
		setSystem_ChangedDate_Fields_6(getContext(), system_changeddate_fields_6);
	}

	/**
	 * Set value of System_ChangedDate_Fields_6
	 * @param context
	 * @param system_changeddate_fields_6
	 */
	public final void setSystem_ChangedDate_Fields_6(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.System_ChangedDate system_changeddate_fields_6)
	{
		if (system_changeddate_fields_6 == null) {
			getMendixObject().setValue(context, MemberNames.System_ChangedDate_Fields_6.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.System_ChangedDate_Fields_6.toString(), system_changeddate_fields_6.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of System_Watermark_Fields_6
	 */
	public final azureextensionmodule.proxies.System_Watermark getSystem_Watermark_Fields_6() throws com.mendix.core.CoreException
	{
		return getSystem_Watermark_Fields_6(getContext());
	}

	/**
	 * @param context
	 * @return value of System_Watermark_Fields_6
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.System_Watermark getSystem_Watermark_Fields_6(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.System_Watermark result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.System_Watermark_Fields_6.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.System_Watermark.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of System_Watermark_Fields_6
	 * @param system_watermark_fields_6
	 */
	public final void setSystem_Watermark_Fields_6(azureextensionmodule.proxies.System_Watermark system_watermark_fields_6)
	{
		setSystem_Watermark_Fields_6(getContext(), system_watermark_fields_6);
	}

	/**
	 * Set value of System_Watermark_Fields_6
	 * @param context
	 * @param system_watermark_fields_6
	 */
	public final void setSystem_Watermark_Fields_6(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.System_Watermark system_watermark_fields_6)
	{
		if (system_watermark_fields_6 == null) {
			getMendixObject().setValue(context, MemberNames.System_Watermark_Fields_6.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.System_Watermark_Fields_6.toString(), system_watermark_fields_6.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of System_Title_Fields_6
	 */
	public final azureextensionmodule.proxies.System_Title getSystem_Title_Fields_6() throws com.mendix.core.CoreException
	{
		return getSystem_Title_Fields_6(getContext());
	}

	/**
	 * @param context
	 * @return value of System_Title_Fields_6
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.System_Title getSystem_Title_Fields_6(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.System_Title result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.System_Title_Fields_6.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.System_Title.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of System_Title_Fields_6
	 * @param system_title_fields_6
	 */
	public final void setSystem_Title_Fields_6(azureextensionmodule.proxies.System_Title system_title_fields_6)
	{
		setSystem_Title_Fields_6(getContext(), system_title_fields_6);
	}

	/**
	 * Set value of System_Title_Fields_6
	 * @param context
	 * @param system_title_fields_6
	 */
	public final void setSystem_Title_Fields_6(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.System_Title system_title_fields_6)
	{
		if (system_title_fields_6 == null) {
			getMendixObject().setValue(context, MemberNames.System_Title_Fields_6.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.System_Title_Fields_6.toString(), system_title_fields_6.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return fields_6MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final azureextensionmodule.proxies.Fields_6 that = (azureextensionmodule.proxies.Fields_6) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
