// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package azureextensionmodule.proxies;

public class Fields_8
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject fields_8MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AzureExtensionModule.Fields_8";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Fields_8_Resource_6("AzureExtensionModule.Fields_8_Resource_6"),
		System_Rev_Fields_8("AzureExtensionModule.System_Rev_Fields_8"),
		System_AuthorizedDate_Fields_8("AzureExtensionModule.System_AuthorizedDate_Fields_8"),
		System_RevisedDate_Fields_8("AzureExtensionModule.System_RevisedDate_Fields_8"),
		System_ChangedDate_Fields_8("AzureExtensionModule.System_ChangedDate_Fields_8"),
		System_Watermark_Fields_8("AzureExtensionModule.System_Watermark_Fields_8"),
		Custom_NPItype_Fields_8("AzureExtensionModule.Custom_NPItype_Fields_8"),
		Custom_MFHours_Fields_8("AzureExtensionModule.Custom_MFHours_Fields_8"),
		Custom_MFinvolved_Fields_8("AzureExtensionModule.Custom_MFinvolved_Fields_8");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Fields_8(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Fields_8(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fields_8MendixObject)
	{
		if (fields_8MendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, fields_8MendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.fields_8MendixObject = fields_8MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Fields_8.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static azureextensionmodule.proxies.Fields_8 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return azureextensionmodule.proxies.Fields_8.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static azureextensionmodule.proxies.Fields_8 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new azureextensionmodule.proxies.Fields_8(context, mendixObject);
	}

	public static azureextensionmodule.proxies.Fields_8 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return azureextensionmodule.proxies.Fields_8.initialize(context, mendixObject);
	}

	public static java.util.List<azureextensionmodule.proxies.Fields_8> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> azureextensionmodule.proxies.Fields_8.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Fields_8_Resource_6
	 */
	public final azureextensionmodule.proxies.Resource_6 getFields_8_Resource_6() throws com.mendix.core.CoreException
	{
		return getFields_8_Resource_6(getContext());
	}

	/**
	 * @param context
	 * @return value of Fields_8_Resource_6
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Resource_6 getFields_8_Resource_6(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Resource_6 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Fields_8_Resource_6.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Resource_6.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Fields_8_Resource_6
	 * @param fields_8_resource_6
	 */
	public final void setFields_8_Resource_6(azureextensionmodule.proxies.Resource_6 fields_8_resource_6)
	{
		setFields_8_Resource_6(getContext(), fields_8_resource_6);
	}

	/**
	 * Set value of Fields_8_Resource_6
	 * @param context
	 * @param fields_8_resource_6
	 */
	public final void setFields_8_Resource_6(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Resource_6 fields_8_resource_6)
	{
		if (fields_8_resource_6 == null) {
			getMendixObject().setValue(context, MemberNames.Fields_8_Resource_6.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Fields_8_Resource_6.toString(), fields_8_resource_6.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of System_Rev_Fields_8
	 */
	public final azureextensionmodule.proxies.System_Rev getSystem_Rev_Fields_8() throws com.mendix.core.CoreException
	{
		return getSystem_Rev_Fields_8(getContext());
	}

	/**
	 * @param context
	 * @return value of System_Rev_Fields_8
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.System_Rev getSystem_Rev_Fields_8(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.System_Rev result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.System_Rev_Fields_8.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.System_Rev.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of System_Rev_Fields_8
	 * @param system_rev_fields_8
	 */
	public final void setSystem_Rev_Fields_8(azureextensionmodule.proxies.System_Rev system_rev_fields_8)
	{
		setSystem_Rev_Fields_8(getContext(), system_rev_fields_8);
	}

	/**
	 * Set value of System_Rev_Fields_8
	 * @param context
	 * @param system_rev_fields_8
	 */
	public final void setSystem_Rev_Fields_8(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.System_Rev system_rev_fields_8)
	{
		if (system_rev_fields_8 == null) {
			getMendixObject().setValue(context, MemberNames.System_Rev_Fields_8.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.System_Rev_Fields_8.toString(), system_rev_fields_8.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of System_AuthorizedDate_Fields_8
	 */
	public final azureextensionmodule.proxies.System_AuthorizedDate getSystem_AuthorizedDate_Fields_8() throws com.mendix.core.CoreException
	{
		return getSystem_AuthorizedDate_Fields_8(getContext());
	}

	/**
	 * @param context
	 * @return value of System_AuthorizedDate_Fields_8
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.System_AuthorizedDate getSystem_AuthorizedDate_Fields_8(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.System_AuthorizedDate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.System_AuthorizedDate_Fields_8.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.System_AuthorizedDate.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of System_AuthorizedDate_Fields_8
	 * @param system_authorizeddate_fields_8
	 */
	public final void setSystem_AuthorizedDate_Fields_8(azureextensionmodule.proxies.System_AuthorizedDate system_authorizeddate_fields_8)
	{
		setSystem_AuthorizedDate_Fields_8(getContext(), system_authorizeddate_fields_8);
	}

	/**
	 * Set value of System_AuthorizedDate_Fields_8
	 * @param context
	 * @param system_authorizeddate_fields_8
	 */
	public final void setSystem_AuthorizedDate_Fields_8(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.System_AuthorizedDate system_authorizeddate_fields_8)
	{
		if (system_authorizeddate_fields_8 == null) {
			getMendixObject().setValue(context, MemberNames.System_AuthorizedDate_Fields_8.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.System_AuthorizedDate_Fields_8.toString(), system_authorizeddate_fields_8.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of System_RevisedDate_Fields_8
	 */
	public final azureextensionmodule.proxies.System_RevisedDate getSystem_RevisedDate_Fields_8() throws com.mendix.core.CoreException
	{
		return getSystem_RevisedDate_Fields_8(getContext());
	}

	/**
	 * @param context
	 * @return value of System_RevisedDate_Fields_8
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.System_RevisedDate getSystem_RevisedDate_Fields_8(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.System_RevisedDate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.System_RevisedDate_Fields_8.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.System_RevisedDate.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of System_RevisedDate_Fields_8
	 * @param system_reviseddate_fields_8
	 */
	public final void setSystem_RevisedDate_Fields_8(azureextensionmodule.proxies.System_RevisedDate system_reviseddate_fields_8)
	{
		setSystem_RevisedDate_Fields_8(getContext(), system_reviseddate_fields_8);
	}

	/**
	 * Set value of System_RevisedDate_Fields_8
	 * @param context
	 * @param system_reviseddate_fields_8
	 */
	public final void setSystem_RevisedDate_Fields_8(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.System_RevisedDate system_reviseddate_fields_8)
	{
		if (system_reviseddate_fields_8 == null) {
			getMendixObject().setValue(context, MemberNames.System_RevisedDate_Fields_8.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.System_RevisedDate_Fields_8.toString(), system_reviseddate_fields_8.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of System_ChangedDate_Fields_8
	 */
	public final azureextensionmodule.proxies.System_ChangedDate getSystem_ChangedDate_Fields_8() throws com.mendix.core.CoreException
	{
		return getSystem_ChangedDate_Fields_8(getContext());
	}

	/**
	 * @param context
	 * @return value of System_ChangedDate_Fields_8
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.System_ChangedDate getSystem_ChangedDate_Fields_8(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.System_ChangedDate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.System_ChangedDate_Fields_8.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.System_ChangedDate.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of System_ChangedDate_Fields_8
	 * @param system_changeddate_fields_8
	 */
	public final void setSystem_ChangedDate_Fields_8(azureextensionmodule.proxies.System_ChangedDate system_changeddate_fields_8)
	{
		setSystem_ChangedDate_Fields_8(getContext(), system_changeddate_fields_8);
	}

	/**
	 * Set value of System_ChangedDate_Fields_8
	 * @param context
	 * @param system_changeddate_fields_8
	 */
	public final void setSystem_ChangedDate_Fields_8(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.System_ChangedDate system_changeddate_fields_8)
	{
		if (system_changeddate_fields_8 == null) {
			getMendixObject().setValue(context, MemberNames.System_ChangedDate_Fields_8.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.System_ChangedDate_Fields_8.toString(), system_changeddate_fields_8.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of System_Watermark_Fields_8
	 */
	public final azureextensionmodule.proxies.System_Watermark getSystem_Watermark_Fields_8() throws com.mendix.core.CoreException
	{
		return getSystem_Watermark_Fields_8(getContext());
	}

	/**
	 * @param context
	 * @return value of System_Watermark_Fields_8
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.System_Watermark getSystem_Watermark_Fields_8(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.System_Watermark result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.System_Watermark_Fields_8.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.System_Watermark.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of System_Watermark_Fields_8
	 * @param system_watermark_fields_8
	 */
	public final void setSystem_Watermark_Fields_8(azureextensionmodule.proxies.System_Watermark system_watermark_fields_8)
	{
		setSystem_Watermark_Fields_8(getContext(), system_watermark_fields_8);
	}

	/**
	 * Set value of System_Watermark_Fields_8
	 * @param context
	 * @param system_watermark_fields_8
	 */
	public final void setSystem_Watermark_Fields_8(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.System_Watermark system_watermark_fields_8)
	{
		if (system_watermark_fields_8 == null) {
			getMendixObject().setValue(context, MemberNames.System_Watermark_Fields_8.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.System_Watermark_Fields_8.toString(), system_watermark_fields_8.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Custom_NPItype_Fields_8
	 */
	public final azureextensionmodule.proxies.Custom_NPItype getCustom_NPItype_Fields_8() throws com.mendix.core.CoreException
	{
		return getCustom_NPItype_Fields_8(getContext());
	}

	/**
	 * @param context
	 * @return value of Custom_NPItype_Fields_8
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Custom_NPItype getCustom_NPItype_Fields_8(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Custom_NPItype result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Custom_NPItype_Fields_8.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Custom_NPItype.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Custom_NPItype_Fields_8
	 * @param custom_npitype_fields_8
	 */
	public final void setCustom_NPItype_Fields_8(azureextensionmodule.proxies.Custom_NPItype custom_npitype_fields_8)
	{
		setCustom_NPItype_Fields_8(getContext(), custom_npitype_fields_8);
	}

	/**
	 * Set value of Custom_NPItype_Fields_8
	 * @param context
	 * @param custom_npitype_fields_8
	 */
	public final void setCustom_NPItype_Fields_8(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Custom_NPItype custom_npitype_fields_8)
	{
		if (custom_npitype_fields_8 == null) {
			getMendixObject().setValue(context, MemberNames.Custom_NPItype_Fields_8.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Custom_NPItype_Fields_8.toString(), custom_npitype_fields_8.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Custom_MFHours_Fields_8
	 */
	public final azureextensionmodule.proxies.Custom_MFHours getCustom_MFHours_Fields_8() throws com.mendix.core.CoreException
	{
		return getCustom_MFHours_Fields_8(getContext());
	}

	/**
	 * @param context
	 * @return value of Custom_MFHours_Fields_8
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Custom_MFHours getCustom_MFHours_Fields_8(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Custom_MFHours result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Custom_MFHours_Fields_8.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Custom_MFHours.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Custom_MFHours_Fields_8
	 * @param custom_mfhours_fields_8
	 */
	public final void setCustom_MFHours_Fields_8(azureextensionmodule.proxies.Custom_MFHours custom_mfhours_fields_8)
	{
		setCustom_MFHours_Fields_8(getContext(), custom_mfhours_fields_8);
	}

	/**
	 * Set value of Custom_MFHours_Fields_8
	 * @param context
	 * @param custom_mfhours_fields_8
	 */
	public final void setCustom_MFHours_Fields_8(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Custom_MFHours custom_mfhours_fields_8)
	{
		if (custom_mfhours_fields_8 == null) {
			getMendixObject().setValue(context, MemberNames.Custom_MFHours_Fields_8.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Custom_MFHours_Fields_8.toString(), custom_mfhours_fields_8.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Custom_MFinvolved_Fields_8
	 */
	public final azureextensionmodule.proxies.Custom_MFinvolved getCustom_MFinvolved_Fields_8() throws com.mendix.core.CoreException
	{
		return getCustom_MFinvolved_Fields_8(getContext());
	}

	/**
	 * @param context
	 * @return value of Custom_MFinvolved_Fields_8
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Custom_MFinvolved getCustom_MFinvolved_Fields_8(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Custom_MFinvolved result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Custom_MFinvolved_Fields_8.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Custom_MFinvolved.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Custom_MFinvolved_Fields_8
	 * @param custom_mfinvolved_fields_8
	 */
	public final void setCustom_MFinvolved_Fields_8(azureextensionmodule.proxies.Custom_MFinvolved custom_mfinvolved_fields_8)
	{
		setCustom_MFinvolved_Fields_8(getContext(), custom_mfinvolved_fields_8);
	}

	/**
	 * Set value of Custom_MFinvolved_Fields_8
	 * @param context
	 * @param custom_mfinvolved_fields_8
	 */
	public final void setCustom_MFinvolved_Fields_8(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Custom_MFinvolved custom_mfinvolved_fields_8)
	{
		if (custom_mfinvolved_fields_8 == null) {
			getMendixObject().setValue(context, MemberNames.Custom_MFinvolved_Fields_8.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Custom_MFinvolved_Fields_8.toString(), custom_mfinvolved_fields_8.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return fields_8MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final azureextensionmodule.proxies.Fields_8 that = (azureextensionmodule.proxies.Fields_8) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
