// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package azureextensionmodule.proxies;

public class JsonObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject jsonObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AzureExtensionModule.JsonObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		System_Id("System_Id"),
		System_WorkItemType("System_WorkItemType"),
		System_Title("System_Title"),
		Microsoft_VSTS_TCM_ReproSteps("Microsoft_VSTS_TCM_ReproSteps"),
		ReleaseId("ReleaseId"),
		WorkItemId("WorkItemId"),
		ValueStreamData("ValueStreamData"),
		ValuestreamName("ValuestreamName"),
		MFID("MFID"),
		Title("Title"),
		_Id("_Id"),
		ReleaseType("ReleaseType"),
		PM200New("PM200New"),
		PM300Plan("PM300Plan"),
		SubPMP("SubPMP"),
		ProjectId("ProjectId"),
		OrganisationId("OrganisationId"),
		TypeId("TypeId"),
		Name("Name"),
		Description("Description"),
		ParentProcessTypeId("ParentProcessTypeId"),
		IsEnabled("IsEnabled"),
		IsDefault("IsDefault"),
		CustomizationType("CustomizationType"),
		Url("Url"),
		IsDisabled("IsDisabled"),
		__Id("__Id"),
		JsonObject_Value("AzureExtensionModule.JsonObject_Value");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JsonObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected JsonObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jsonObjectMendixObject)
	{
		if (jsonObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, jsonObjectMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.jsonObjectMendixObject = jsonObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'JsonObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static azureextensionmodule.proxies.JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return azureextensionmodule.proxies.JsonObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static azureextensionmodule.proxies.JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new azureextensionmodule.proxies.JsonObject(context, mendixObject);
	}

	public static azureextensionmodule.proxies.JsonObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return azureextensionmodule.proxies.JsonObject.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of System_Id
	 */
	public final java.lang.Integer getSystem_Id()
	{
		return getSystem_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of System_Id
	 */
	public final java.lang.Integer getSystem_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.System_Id.toString());
	}

	/**
	 * Set value of System_Id
	 * @param system_id
	 */
	public final void setSystem_Id(java.lang.Integer system_id)
	{
		setSystem_Id(getContext(), system_id);
	}

	/**
	 * Set value of System_Id
	 * @param context
	 * @param system_id
	 */
	public final void setSystem_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer system_id)
	{
		getMendixObject().setValue(context, MemberNames.System_Id.toString(), system_id);
	}

	/**
	 * @return value of System_WorkItemType
	 */
	public final java.lang.String getSystem_WorkItemType()
	{
		return getSystem_WorkItemType(getContext());
	}

	/**
	 * @param context
	 * @return value of System_WorkItemType
	 */
	public final java.lang.String getSystem_WorkItemType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.System_WorkItemType.toString());
	}

	/**
	 * Set value of System_WorkItemType
	 * @param system_workitemtype
	 */
	public final void setSystem_WorkItemType(java.lang.String system_workitemtype)
	{
		setSystem_WorkItemType(getContext(), system_workitemtype);
	}

	/**
	 * Set value of System_WorkItemType
	 * @param context
	 * @param system_workitemtype
	 */
	public final void setSystem_WorkItemType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String system_workitemtype)
	{
		getMendixObject().setValue(context, MemberNames.System_WorkItemType.toString(), system_workitemtype);
	}

	/**
	 * @return value of System_Title
	 */
	public final java.lang.String getSystem_Title()
	{
		return getSystem_Title(getContext());
	}

	/**
	 * @param context
	 * @return value of System_Title
	 */
	public final java.lang.String getSystem_Title(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.System_Title.toString());
	}

	/**
	 * Set value of System_Title
	 * @param system_title
	 */
	public final void setSystem_Title(java.lang.String system_title)
	{
		setSystem_Title(getContext(), system_title);
	}

	/**
	 * Set value of System_Title
	 * @param context
	 * @param system_title
	 */
	public final void setSystem_Title(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String system_title)
	{
		getMendixObject().setValue(context, MemberNames.System_Title.toString(), system_title);
	}

	/**
	 * @return value of Microsoft_VSTS_TCM_ReproSteps
	 */
	public final java.lang.String getMicrosoft_VSTS_TCM_ReproSteps()
	{
		return getMicrosoft_VSTS_TCM_ReproSteps(getContext());
	}

	/**
	 * @param context
	 * @return value of Microsoft_VSTS_TCM_ReproSteps
	 */
	public final java.lang.String getMicrosoft_VSTS_TCM_ReproSteps(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Microsoft_VSTS_TCM_ReproSteps.toString());
	}

	/**
	 * Set value of Microsoft_VSTS_TCM_ReproSteps
	 * @param microsoft_vsts_tcm_reprosteps
	 */
	public final void setMicrosoft_VSTS_TCM_ReproSteps(java.lang.String microsoft_vsts_tcm_reprosteps)
	{
		setMicrosoft_VSTS_TCM_ReproSteps(getContext(), microsoft_vsts_tcm_reprosteps);
	}

	/**
	 * Set value of Microsoft_VSTS_TCM_ReproSteps
	 * @param context
	 * @param microsoft_vsts_tcm_reprosteps
	 */
	public final void setMicrosoft_VSTS_TCM_ReproSteps(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String microsoft_vsts_tcm_reprosteps)
	{
		getMendixObject().setValue(context, MemberNames.Microsoft_VSTS_TCM_ReproSteps.toString(), microsoft_vsts_tcm_reprosteps);
	}

	/**
	 * @return value of ReleaseId
	 */
	public final java.lang.String getReleaseId()
	{
		return getReleaseId(getContext());
	}

	/**
	 * @param context
	 * @return value of ReleaseId
	 */
	public final java.lang.String getReleaseId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReleaseId.toString());
	}

	/**
	 * Set value of ReleaseId
	 * @param releaseid
	 */
	public final void setReleaseId(java.lang.String releaseid)
	{
		setReleaseId(getContext(), releaseid);
	}

	/**
	 * Set value of ReleaseId
	 * @param context
	 * @param releaseid
	 */
	public final void setReleaseId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String releaseid)
	{
		getMendixObject().setValue(context, MemberNames.ReleaseId.toString(), releaseid);
	}

	/**
	 * @return value of WorkItemId
	 */
	public final java.lang.String getWorkItemId()
	{
		return getWorkItemId(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkItemId
	 */
	public final java.lang.String getWorkItemId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkItemId.toString());
	}

	/**
	 * Set value of WorkItemId
	 * @param workitemid
	 */
	public final void setWorkItemId(java.lang.String workitemid)
	{
		setWorkItemId(getContext(), workitemid);
	}

	/**
	 * Set value of WorkItemId
	 * @param context
	 * @param workitemid
	 */
	public final void setWorkItemId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workitemid)
	{
		getMendixObject().setValue(context, MemberNames.WorkItemId.toString(), workitemid);
	}

	/**
	 * @return value of ValueStreamData
	 */
	public final java.lang.String getValueStreamData()
	{
		return getValueStreamData(getContext());
	}

	/**
	 * @param context
	 * @return value of ValueStreamData
	 */
	public final java.lang.String getValueStreamData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ValueStreamData.toString());
	}

	/**
	 * Set value of ValueStreamData
	 * @param valuestreamdata
	 */
	public final void setValueStreamData(java.lang.String valuestreamdata)
	{
		setValueStreamData(getContext(), valuestreamdata);
	}

	/**
	 * Set value of ValueStreamData
	 * @param context
	 * @param valuestreamdata
	 */
	public final void setValueStreamData(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String valuestreamdata)
	{
		getMendixObject().setValue(context, MemberNames.ValueStreamData.toString(), valuestreamdata);
	}

	/**
	 * @return value of ValuestreamName
	 */
	public final java.lang.String getValuestreamName()
	{
		return getValuestreamName(getContext());
	}

	/**
	 * @param context
	 * @return value of ValuestreamName
	 */
	public final java.lang.String getValuestreamName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ValuestreamName.toString());
	}

	/**
	 * Set value of ValuestreamName
	 * @param valuestreamname
	 */
	public final void setValuestreamName(java.lang.String valuestreamname)
	{
		setValuestreamName(getContext(), valuestreamname);
	}

	/**
	 * Set value of ValuestreamName
	 * @param context
	 * @param valuestreamname
	 */
	public final void setValuestreamName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String valuestreamname)
	{
		getMendixObject().setValue(context, MemberNames.ValuestreamName.toString(), valuestreamname);
	}

	/**
	 * @return value of MFID
	 */
	public final java.lang.String getMFID()
	{
		return getMFID(getContext());
	}

	/**
	 * @param context
	 * @return value of MFID
	 */
	public final java.lang.String getMFID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MFID.toString());
	}

	/**
	 * Set value of MFID
	 * @param mfid
	 */
	public final void setMFID(java.lang.String mfid)
	{
		setMFID(getContext(), mfid);
	}

	/**
	 * Set value of MFID
	 * @param context
	 * @param mfid
	 */
	public final void setMFID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mfid)
	{
		getMendixObject().setValue(context, MemberNames.MFID.toString(), mfid);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of _Id
	 */
	public final java.lang.Integer get_Id()
	{
		return get_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of _Id
	 */
	public final java.lang.Integer get_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames._Id.toString());
	}

	/**
	 * Set value of _Id
	 * @param _id
	 */
	public final void set_Id(java.lang.Integer _id)
	{
		set_Id(getContext(), _id);
	}

	/**
	 * Set value of _Id
	 * @param context
	 * @param _id
	 */
	public final void set_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer _id)
	{
		getMendixObject().setValue(context, MemberNames._Id.toString(), _id);
	}

	/**
	 * @return value of ReleaseType
	 */
	public final java.lang.String getReleaseType()
	{
		return getReleaseType(getContext());
	}

	/**
	 * @param context
	 * @return value of ReleaseType
	 */
	public final java.lang.String getReleaseType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReleaseType.toString());
	}

	/**
	 * Set value of ReleaseType
	 * @param releasetype
	 */
	public final void setReleaseType(java.lang.String releasetype)
	{
		setReleaseType(getContext(), releasetype);
	}

	/**
	 * Set value of ReleaseType
	 * @param context
	 * @param releasetype
	 */
	public final void setReleaseType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String releasetype)
	{
		getMendixObject().setValue(context, MemberNames.ReleaseType.toString(), releasetype);
	}

	/**
	 * @return value of PM200New
	 */
	public final java.lang.String getPM200New()
	{
		return getPM200New(getContext());
	}

	/**
	 * @param context
	 * @return value of PM200New
	 */
	public final java.lang.String getPM200New(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PM200New.toString());
	}

	/**
	 * Set value of PM200New
	 * @param pm200new
	 */
	public final void setPM200New(java.lang.String pm200new)
	{
		setPM200New(getContext(), pm200new);
	}

	/**
	 * Set value of PM200New
	 * @param context
	 * @param pm200new
	 */
	public final void setPM200New(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pm200new)
	{
		getMendixObject().setValue(context, MemberNames.PM200New.toString(), pm200new);
	}

	/**
	 * @return value of PM300Plan
	 */
	public final java.lang.String getPM300Plan()
	{
		return getPM300Plan(getContext());
	}

	/**
	 * @param context
	 * @return value of PM300Plan
	 */
	public final java.lang.String getPM300Plan(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PM300Plan.toString());
	}

	/**
	 * Set value of PM300Plan
	 * @param pm300plan
	 */
	public final void setPM300Plan(java.lang.String pm300plan)
	{
		setPM300Plan(getContext(), pm300plan);
	}

	/**
	 * Set value of PM300Plan
	 * @param context
	 * @param pm300plan
	 */
	public final void setPM300Plan(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pm300plan)
	{
		getMendixObject().setValue(context, MemberNames.PM300Plan.toString(), pm300plan);
	}

	/**
	 * @return value of SubPMP
	 */
	public final java.lang.String getSubPMP()
	{
		return getSubPMP(getContext());
	}

	/**
	 * @param context
	 * @return value of SubPMP
	 */
	public final java.lang.String getSubPMP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubPMP.toString());
	}

	/**
	 * Set value of SubPMP
	 * @param subpmp
	 */
	public final void setSubPMP(java.lang.String subpmp)
	{
		setSubPMP(getContext(), subpmp);
	}

	/**
	 * Set value of SubPMP
	 * @param context
	 * @param subpmp
	 */
	public final void setSubPMP(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subpmp)
	{
		getMendixObject().setValue(context, MemberNames.SubPMP.toString(), subpmp);
	}

	/**
	 * @return value of ProjectId
	 */
	public final java.lang.String getProjectId()
	{
		return getProjectId(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectId
	 */
	public final java.lang.String getProjectId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProjectId.toString());
	}

	/**
	 * Set value of ProjectId
	 * @param projectid
	 */
	public final void setProjectId(java.lang.String projectid)
	{
		setProjectId(getContext(), projectid);
	}

	/**
	 * Set value of ProjectId
	 * @param context
	 * @param projectid
	 */
	public final void setProjectId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String projectid)
	{
		getMendixObject().setValue(context, MemberNames.ProjectId.toString(), projectid);
	}

	/**
	 * @return value of OrganisationId
	 */
	public final java.lang.String getOrganisationId()
	{
		return getOrganisationId(getContext());
	}

	/**
	 * @param context
	 * @return value of OrganisationId
	 */
	public final java.lang.String getOrganisationId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrganisationId.toString());
	}

	/**
	 * Set value of OrganisationId
	 * @param organisationid
	 */
	public final void setOrganisationId(java.lang.String organisationid)
	{
		setOrganisationId(getContext(), organisationid);
	}

	/**
	 * Set value of OrganisationId
	 * @param context
	 * @param organisationid
	 */
	public final void setOrganisationId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String organisationid)
	{
		getMendixObject().setValue(context, MemberNames.OrganisationId.toString(), organisationid);
	}

	/**
	 * @return value of TypeId
	 */
	public final java.lang.String getTypeId()
	{
		return getTypeId(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeId
	 */
	public final java.lang.String getTypeId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TypeId.toString());
	}

	/**
	 * Set value of TypeId
	 * @param typeid
	 */
	public final void setTypeId(java.lang.String typeid)
	{
		setTypeId(getContext(), typeid);
	}

	/**
	 * Set value of TypeId
	 * @param context
	 * @param typeid
	 */
	public final void setTypeId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String typeid)
	{
		getMendixObject().setValue(context, MemberNames.TypeId.toString(), typeid);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of ParentProcessTypeId
	 */
	public final java.lang.String getParentProcessTypeId()
	{
		return getParentProcessTypeId(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentProcessTypeId
	 */
	public final java.lang.String getParentProcessTypeId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParentProcessTypeId.toString());
	}

	/**
	 * Set value of ParentProcessTypeId
	 * @param parentprocesstypeid
	 */
	public final void setParentProcessTypeId(java.lang.String parentprocesstypeid)
	{
		setParentProcessTypeId(getContext(), parentprocesstypeid);
	}

	/**
	 * Set value of ParentProcessTypeId
	 * @param context
	 * @param parentprocesstypeid
	 */
	public final void setParentProcessTypeId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parentprocesstypeid)
	{
		getMendixObject().setValue(context, MemberNames.ParentProcessTypeId.toString(), parentprocesstypeid);
	}

	/**
	 * @return value of IsEnabled
	 */
	public final java.lang.Boolean getIsEnabled()
	{
		return getIsEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of IsEnabled
	 */
	public final java.lang.Boolean getIsEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsEnabled.toString());
	}

	/**
	 * Set value of IsEnabled
	 * @param isenabled
	 */
	public final void setIsEnabled(java.lang.Boolean isenabled)
	{
		setIsEnabled(getContext(), isenabled);
	}

	/**
	 * Set value of IsEnabled
	 * @param context
	 * @param isenabled
	 */
	public final void setIsEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isenabled)
	{
		getMendixObject().setValue(context, MemberNames.IsEnabled.toString(), isenabled);
	}

	/**
	 * @return value of IsDefault
	 */
	public final java.lang.Boolean getIsDefault()
	{
		return getIsDefault(getContext());
	}

	/**
	 * @param context
	 * @return value of IsDefault
	 */
	public final java.lang.Boolean getIsDefault(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsDefault.toString());
	}

	/**
	 * Set value of IsDefault
	 * @param isdefault
	 */
	public final void setIsDefault(java.lang.Boolean isdefault)
	{
		setIsDefault(getContext(), isdefault);
	}

	/**
	 * Set value of IsDefault
	 * @param context
	 * @param isdefault
	 */
	public final void setIsDefault(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdefault)
	{
		getMendixObject().setValue(context, MemberNames.IsDefault.toString(), isdefault);
	}

	/**
	 * @return value of CustomizationType
	 */
	public final java.lang.String getCustomizationType()
	{
		return getCustomizationType(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomizationType
	 */
	public final java.lang.String getCustomizationType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CustomizationType.toString());
	}

	/**
	 * Set value of CustomizationType
	 * @param customizationtype
	 */
	public final void setCustomizationType(java.lang.String customizationtype)
	{
		setCustomizationType(getContext(), customizationtype);
	}

	/**
	 * Set value of CustomizationType
	 * @param context
	 * @param customizationtype
	 */
	public final void setCustomizationType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customizationtype)
	{
		getMendixObject().setValue(context, MemberNames.CustomizationType.toString(), customizationtype);
	}

	/**
	 * @return value of Url
	 */
	public final java.lang.String getUrl()
	{
		return getUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of Url
	 */
	public final java.lang.String getUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Url.toString());
	}

	/**
	 * Set value of Url
	 * @param url
	 */
	public final void setUrl(java.lang.String url)
	{
		setUrl(getContext(), url);
	}

	/**
	 * Set value of Url
	 * @param context
	 * @param url
	 */
	public final void setUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String url)
	{
		getMendixObject().setValue(context, MemberNames.Url.toString(), url);
	}

	/**
	 * @return value of IsDisabled
	 */
	public final java.lang.Boolean getIsDisabled()
	{
		return getIsDisabled(getContext());
	}

	/**
	 * @param context
	 * @return value of IsDisabled
	 */
	public final java.lang.Boolean getIsDisabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsDisabled.toString());
	}

	/**
	 * Set value of IsDisabled
	 * @param isdisabled
	 */
	public final void setIsDisabled(java.lang.Boolean isdisabled)
	{
		setIsDisabled(getContext(), isdisabled);
	}

	/**
	 * Set value of IsDisabled
	 * @param context
	 * @param isdisabled
	 */
	public final void setIsDisabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdisabled)
	{
		getMendixObject().setValue(context, MemberNames.IsDisabled.toString(), isdisabled);
	}

	/**
	 * @return value of __Id
	 */
	public final java.lang.String get__Id()
	{
		return get__Id(getContext());
	}

	/**
	 * @param context
	 * @return value of __Id
	 */
	public final java.lang.String get__Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.__Id.toString());
	}

	/**
	 * Set value of __Id
	 * @param __id
	 */
	public final void set__Id(java.lang.String __id)
	{
		set__Id(getContext(), __id);
	}

	/**
	 * Set value of __Id
	 * @param context
	 * @param __id
	 */
	public final void set__Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String __id)
	{
		getMendixObject().setValue(context, MemberNames.__Id.toString(), __id);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of JsonObject_Value
	 */
	public final azureextensionmodule.proxies.Value getJsonObject_Value() throws com.mendix.core.CoreException
	{
		return getJsonObject_Value(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonObject_Value
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Value getJsonObject_Value(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Value result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JsonObject_Value.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Value.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of JsonObject_Value
	 * @param jsonobject_value
	 */
	public final void setJsonObject_Value(azureextensionmodule.proxies.Value jsonobject_value)
	{
		setJsonObject_Value(getContext(), jsonobject_value);
	}

	/**
	 * Set value of JsonObject_Value
	 * @param context
	 * @param jsonobject_value
	 */
	public final void setJsonObject_Value(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Value jsonobject_value)
	{
		if (jsonobject_value == null) {
			getMendixObject().setValue(context, MemberNames.JsonObject_Value.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.JsonObject_Value.toString(), jsonobject_value.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return jsonObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final azureextensionmodule.proxies.JsonObject that = (azureextensionmodule.proxies.JsonObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
