// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package azureextensionmodule.proxies;

public class ResourceContainers
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resourceContainersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AzureExtensionModule.ResourceContainers";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ResourceContainers_Root("AzureExtensionModule.ResourceContainers_Root"),
		Collection_ResourceContainers("AzureExtensionModule.Collection_ResourceContainers"),
		Account_ResourceContainers("AzureExtensionModule.Account_ResourceContainers"),
		Project_ResourceContainers("AzureExtensionModule.Project_ResourceContainers");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResourceContainers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResourceContainers(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resourceContainersMendixObject)
	{
		if (resourceContainersMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, resourceContainersMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resourceContainersMendixObject = resourceContainersMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ResourceContainers.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static azureextensionmodule.proxies.ResourceContainers initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return azureextensionmodule.proxies.ResourceContainers.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static azureextensionmodule.proxies.ResourceContainers initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new azureextensionmodule.proxies.ResourceContainers(context, mendixObject);
	}

	public static azureextensionmodule.proxies.ResourceContainers load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return azureextensionmodule.proxies.ResourceContainers.initialize(context, mendixObject);
	}

	public static java.util.List<azureextensionmodule.proxies.ResourceContainers> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> azureextensionmodule.proxies.ResourceContainers.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResourceContainers_Root
	 */
	public final azureextensionmodule.proxies.Root getResourceContainers_Root() throws com.mendix.core.CoreException
	{
		return getResourceContainers_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceContainers_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Root getResourceContainers_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResourceContainers_Root.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResourceContainers_Root
	 * @param resourcecontainers_root
	 */
	public final void setResourceContainers_Root(azureextensionmodule.proxies.Root resourcecontainers_root)
	{
		setResourceContainers_Root(getContext(), resourcecontainers_root);
	}

	/**
	 * Set value of ResourceContainers_Root
	 * @param context
	 * @param resourcecontainers_root
	 */
	public final void setResourceContainers_Root(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Root resourcecontainers_root)
	{
		if (resourcecontainers_root == null) {
			getMendixObject().setValue(context, MemberNames.ResourceContainers_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResourceContainers_Root.toString(), resourcecontainers_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Collection_ResourceContainers
	 */
	public final azureextensionmodule.proxies.Collection getCollection_ResourceContainers() throws com.mendix.core.CoreException
	{
		return getCollection_ResourceContainers(getContext());
	}

	/**
	 * @param context
	 * @return value of Collection_ResourceContainers
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Collection getCollection_ResourceContainers(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Collection result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Collection_ResourceContainers.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Collection.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Collection_ResourceContainers
	 * @param collection_resourcecontainers
	 */
	public final void setCollection_ResourceContainers(azureextensionmodule.proxies.Collection collection_resourcecontainers)
	{
		setCollection_ResourceContainers(getContext(), collection_resourcecontainers);
	}

	/**
	 * Set value of Collection_ResourceContainers
	 * @param context
	 * @param collection_resourcecontainers
	 */
	public final void setCollection_ResourceContainers(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Collection collection_resourcecontainers)
	{
		if (collection_resourcecontainers == null) {
			getMendixObject().setValue(context, MemberNames.Collection_ResourceContainers.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Collection_ResourceContainers.toString(), collection_resourcecontainers.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Account_ResourceContainers
	 */
	public final azureextensionmodule.proxies.Account getAccount_ResourceContainers() throws com.mendix.core.CoreException
	{
		return getAccount_ResourceContainers(getContext());
	}

	/**
	 * @param context
	 * @return value of Account_ResourceContainers
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Account getAccount_ResourceContainers(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Account_ResourceContainers.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Account_ResourceContainers
	 * @param account_resourcecontainers
	 */
	public final void setAccount_ResourceContainers(azureextensionmodule.proxies.Account account_resourcecontainers)
	{
		setAccount_ResourceContainers(getContext(), account_resourcecontainers);
	}

	/**
	 * Set value of Account_ResourceContainers
	 * @param context
	 * @param account_resourcecontainers
	 */
	public final void setAccount_ResourceContainers(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Account account_resourcecontainers)
	{
		if (account_resourcecontainers == null) {
			getMendixObject().setValue(context, MemberNames.Account_ResourceContainers.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Account_ResourceContainers.toString(), account_resourcecontainers.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Project_ResourceContainers
	 */
	public final azureextensionmodule.proxies.Project getProject_ResourceContainers() throws com.mendix.core.CoreException
	{
		return getProject_ResourceContainers(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_ResourceContainers
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Project getProject_ResourceContainers(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Project result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Project_ResourceContainers.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Project.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Project_ResourceContainers
	 * @param project_resourcecontainers
	 */
	public final void setProject_ResourceContainers(azureextensionmodule.proxies.Project project_resourcecontainers)
	{
		setProject_ResourceContainers(getContext(), project_resourcecontainers);
	}

	/**
	 * Set value of Project_ResourceContainers
	 * @param context
	 * @param project_resourcecontainers
	 */
	public final void setProject_ResourceContainers(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Project project_resourcecontainers)
	{
		if (project_resourcecontainers == null) {
			getMendixObject().setValue(context, MemberNames.Project_ResourceContainers.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Project_ResourceContainers.toString(), project_resourcecontainers.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resourceContainersMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final azureextensionmodule.proxies.ResourceContainers that = (azureextensionmodule.proxies.ResourceContainers) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
