// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package azureextensionmodule.proxies;

public class Resource_4
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resource_4MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AzureExtensionModule.Resource_4";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		WorkItemId("WorkItemId"),
		Rev("Rev"),
		RevisedDate("RevisedDate"),
		Url("Url"),
		Resource_4_Root("AzureExtensionModule.Resource_4_Root"),
		RevisedBy_Resource_4("AzureExtensionModule.RevisedBy_Resource_4"),
		Fields_6_Resource_4("AzureExtensionModule.Fields_6_Resource_4"),
		_links_2_Resource_4("AzureExtensionModule._links_2_Resource_4"),
		Revision_Resource_4("AzureExtensionModule.Revision_Resource_4");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Resource_4(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Resource_4(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resource_4MendixObject)
	{
		if (resource_4MendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, resource_4MendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resource_4MendixObject = resource_4MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Resource_4.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static azureextensionmodule.proxies.Resource_4 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return azureextensionmodule.proxies.Resource_4.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static azureextensionmodule.proxies.Resource_4 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new azureextensionmodule.proxies.Resource_4(context, mendixObject);
	}

	public static azureextensionmodule.proxies.Resource_4 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return azureextensionmodule.proxies.Resource_4.initialize(context, mendixObject);
	}

	public static java.util.List<azureextensionmodule.proxies.Resource_4> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> azureextensionmodule.proxies.Resource_4.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.Integer get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.Integer get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.Integer _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of WorkItemId
	 */
	public final java.lang.Integer getWorkItemId()
	{
		return getWorkItemId(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkItemId
	 */
	public final java.lang.Integer getWorkItemId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.WorkItemId.toString());
	}

	/**
	 * Set value of WorkItemId
	 * @param workitemid
	 */
	public final void setWorkItemId(java.lang.Integer workitemid)
	{
		setWorkItemId(getContext(), workitemid);
	}

	/**
	 * Set value of WorkItemId
	 * @param context
	 * @param workitemid
	 */
	public final void setWorkItemId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer workitemid)
	{
		getMendixObject().setValue(context, MemberNames.WorkItemId.toString(), workitemid);
	}

	/**
	 * @return value of Rev
	 */
	public final java.lang.Integer getRev()
	{
		return getRev(getContext());
	}

	/**
	 * @param context
	 * @return value of Rev
	 */
	public final java.lang.Integer getRev(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Rev.toString());
	}

	/**
	 * Set value of Rev
	 * @param rev
	 */
	public final void setRev(java.lang.Integer rev)
	{
		setRev(getContext(), rev);
	}

	/**
	 * Set value of Rev
	 * @param context
	 * @param rev
	 */
	public final void setRev(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer rev)
	{
		getMendixObject().setValue(context, MemberNames.Rev.toString(), rev);
	}

	/**
	 * @return value of RevisedDate
	 */
	public final java.util.Date getRevisedDate()
	{
		return getRevisedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of RevisedDate
	 */
	public final java.util.Date getRevisedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.RevisedDate.toString());
	}

	/**
	 * Set value of RevisedDate
	 * @param reviseddate
	 */
	public final void setRevisedDate(java.util.Date reviseddate)
	{
		setRevisedDate(getContext(), reviseddate);
	}

	/**
	 * Set value of RevisedDate
	 * @param context
	 * @param reviseddate
	 */
	public final void setRevisedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date reviseddate)
	{
		getMendixObject().setValue(context, MemberNames.RevisedDate.toString(), reviseddate);
	}

	/**
	 * @return value of Url
	 */
	public final java.lang.String getUrl()
	{
		return getUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of Url
	 */
	public final java.lang.String getUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Url.toString());
	}

	/**
	 * Set value of Url
	 * @param url
	 */
	public final void setUrl(java.lang.String url)
	{
		setUrl(getContext(), url);
	}

	/**
	 * Set value of Url
	 * @param context
	 * @param url
	 */
	public final void setUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String url)
	{
		getMendixObject().setValue(context, MemberNames.Url.toString(), url);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Resource_4_Root
	 */
	public final azureextensionmodule.proxies.Root getResource_4_Root() throws com.mendix.core.CoreException
	{
		return getResource_4_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Resource_4_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Root getResource_4_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Resource_4_Root.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Resource_4_Root
	 * @param resource_4_root
	 */
	public final void setResource_4_Root(azureextensionmodule.proxies.Root resource_4_root)
	{
		setResource_4_Root(getContext(), resource_4_root);
	}

	/**
	 * Set value of Resource_4_Root
	 * @param context
	 * @param resource_4_root
	 */
	public final void setResource_4_Root(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Root resource_4_root)
	{
		if (resource_4_root == null) {
			getMendixObject().setValue(context, MemberNames.Resource_4_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Resource_4_Root.toString(), resource_4_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RevisedBy_Resource_4
	 */
	public final azureextensionmodule.proxies.RevisedBy getRevisedBy_Resource_4() throws com.mendix.core.CoreException
	{
		return getRevisedBy_Resource_4(getContext());
	}

	/**
	 * @param context
	 * @return value of RevisedBy_Resource_4
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.RevisedBy getRevisedBy_Resource_4(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.RevisedBy result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RevisedBy_Resource_4.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.RevisedBy.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RevisedBy_Resource_4
	 * @param revisedby_resource_4
	 */
	public final void setRevisedBy_Resource_4(azureextensionmodule.proxies.RevisedBy revisedby_resource_4)
	{
		setRevisedBy_Resource_4(getContext(), revisedby_resource_4);
	}

	/**
	 * Set value of RevisedBy_Resource_4
	 * @param context
	 * @param revisedby_resource_4
	 */
	public final void setRevisedBy_Resource_4(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.RevisedBy revisedby_resource_4)
	{
		if (revisedby_resource_4 == null) {
			getMendixObject().setValue(context, MemberNames.RevisedBy_Resource_4.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RevisedBy_Resource_4.toString(), revisedby_resource_4.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Fields_6_Resource_4
	 */
	public final azureextensionmodule.proxies.Fields_6 getFields_6_Resource_4() throws com.mendix.core.CoreException
	{
		return getFields_6_Resource_4(getContext());
	}

	/**
	 * @param context
	 * @return value of Fields_6_Resource_4
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Fields_6 getFields_6_Resource_4(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Fields_6 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Fields_6_Resource_4.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Fields_6.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Fields_6_Resource_4
	 * @param fields_6_resource_4
	 */
	public final void setFields_6_Resource_4(azureextensionmodule.proxies.Fields_6 fields_6_resource_4)
	{
		setFields_6_Resource_4(getContext(), fields_6_resource_4);
	}

	/**
	 * Set value of Fields_6_Resource_4
	 * @param context
	 * @param fields_6_resource_4
	 */
	public final void setFields_6_Resource_4(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Fields_6 fields_6_resource_4)
	{
		if (fields_6_resource_4 == null) {
			getMendixObject().setValue(context, MemberNames.Fields_6_Resource_4.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Fields_6_Resource_4.toString(), fields_6_resource_4.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of _links_2_Resource_4
	 */
	public final azureextensionmodule.proxies._links_2 get_links_2_Resource_4() throws com.mendix.core.CoreException
	{
		return get_links_2_Resource_4(getContext());
	}

	/**
	 * @param context
	 * @return value of _links_2_Resource_4
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies._links_2 get_links_2_Resource_4(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies._links_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames._links_2_Resource_4.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies._links_2.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of _links_2_Resource_4
	 * @param _links_2_resource_4
	 */
	public final void set_links_2_Resource_4(azureextensionmodule.proxies._links_2 _links_2_resource_4)
	{
		set_links_2_Resource_4(getContext(), _links_2_resource_4);
	}

	/**
	 * Set value of _links_2_Resource_4
	 * @param context
	 * @param _links_2_resource_4
	 */
	public final void set_links_2_Resource_4(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies._links_2 _links_2_resource_4)
	{
		if (_links_2_resource_4 == null) {
			getMendixObject().setValue(context, MemberNames._links_2_Resource_4.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames._links_2_Resource_4.toString(), _links_2_resource_4.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Revision_Resource_4
	 */
	public final azureextensionmodule.proxies.Revision getRevision_Resource_4() throws com.mendix.core.CoreException
	{
		return getRevision_Resource_4(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision_Resource_4
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Revision getRevision_Resource_4(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Revision result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Revision_Resource_4.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Revision.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Revision_Resource_4
	 * @param revision_resource_4
	 */
	public final void setRevision_Resource_4(azureextensionmodule.proxies.Revision revision_resource_4)
	{
		setRevision_Resource_4(getContext(), revision_resource_4);
	}

	/**
	 * Set value of Revision_Resource_4
	 * @param context
	 * @param revision_resource_4
	 */
	public final void setRevision_Resource_4(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Revision revision_resource_4)
	{
		if (revision_resource_4 == null) {
			getMendixObject().setValue(context, MemberNames.Revision_Resource_4.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Revision_Resource_4.toString(), revision_resource_4.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resource_4MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final azureextensionmodule.proxies.Resource_4 that = (azureextensionmodule.proxies.Resource_4) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
