// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package azureextensionmodule.proxies;

public class Revision
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject revisionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AzureExtensionModule.Revision";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		Rev("Rev"),
		Url("Url"),
		Revision_Resource_4("AzureExtensionModule.Revision_Resource_4"),
		Fields_2_Revision("AzureExtensionModule.Fields_2_Revision"),
		Revision_Resource_6("AzureExtensionModule.Revision_Resource_6");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Revision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Revision(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject revisionMendixObject)
	{
		if (revisionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, revisionMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.revisionMendixObject = revisionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Revision.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static azureextensionmodule.proxies.Revision initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return azureextensionmodule.proxies.Revision.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static azureextensionmodule.proxies.Revision initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new azureextensionmodule.proxies.Revision(context, mendixObject);
	}

	public static azureextensionmodule.proxies.Revision load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return azureextensionmodule.proxies.Revision.initialize(context, mendixObject);
	}

	public static java.util.List<azureextensionmodule.proxies.Revision> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> azureextensionmodule.proxies.Revision.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.Integer get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.Integer get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.Integer _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Rev
	 */
	public final java.lang.Integer getRev()
	{
		return getRev(getContext());
	}

	/**
	 * @param context
	 * @return value of Rev
	 */
	public final java.lang.Integer getRev(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Rev.toString());
	}

	/**
	 * Set value of Rev
	 * @param rev
	 */
	public final void setRev(java.lang.Integer rev)
	{
		setRev(getContext(), rev);
	}

	/**
	 * Set value of Rev
	 * @param context
	 * @param rev
	 */
	public final void setRev(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer rev)
	{
		getMendixObject().setValue(context, MemberNames.Rev.toString(), rev);
	}

	/**
	 * @return value of Url
	 */
	public final java.lang.String getUrl()
	{
		return getUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of Url
	 */
	public final java.lang.String getUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Url.toString());
	}

	/**
	 * Set value of Url
	 * @param url
	 */
	public final void setUrl(java.lang.String url)
	{
		setUrl(getContext(), url);
	}

	/**
	 * Set value of Url
	 * @param context
	 * @param url
	 */
	public final void setUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String url)
	{
		getMendixObject().setValue(context, MemberNames.Url.toString(), url);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Revision_Resource_4
	 */
	public final azureextensionmodule.proxies.Resource_4 getRevision_Resource_4() throws com.mendix.core.CoreException
	{
		return getRevision_Resource_4(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision_Resource_4
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Resource_4 getRevision_Resource_4(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Resource_4 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Revision_Resource_4.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Resource_4.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Revision_Resource_4
	 * @param revision_resource_4
	 */
	public final void setRevision_Resource_4(azureextensionmodule.proxies.Resource_4 revision_resource_4)
	{
		setRevision_Resource_4(getContext(), revision_resource_4);
	}

	/**
	 * Set value of Revision_Resource_4
	 * @param context
	 * @param revision_resource_4
	 */
	public final void setRevision_Resource_4(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Resource_4 revision_resource_4)
	{
		if (revision_resource_4 == null) {
			getMendixObject().setValue(context, MemberNames.Revision_Resource_4.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Revision_Resource_4.toString(), revision_resource_4.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Fields_2_Revision
	 */
	public final azureextensionmodule.proxies.Fields_2 getFields_2_Revision() throws com.mendix.core.CoreException
	{
		return getFields_2_Revision(getContext());
	}

	/**
	 * @param context
	 * @return value of Fields_2_Revision
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Fields_2 getFields_2_Revision(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Fields_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Fields_2_Revision.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Fields_2.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Fields_2_Revision
	 * @param fields_2_revision
	 */
	public final void setFields_2_Revision(azureextensionmodule.proxies.Fields_2 fields_2_revision)
	{
		setFields_2_Revision(getContext(), fields_2_revision);
	}

	/**
	 * Set value of Fields_2_Revision
	 * @param context
	 * @param fields_2_revision
	 */
	public final void setFields_2_Revision(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Fields_2 fields_2_revision)
	{
		if (fields_2_revision == null) {
			getMendixObject().setValue(context, MemberNames.Fields_2_Revision.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Fields_2_Revision.toString(), fields_2_revision.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Revision_Resource_6
	 */
	public final azureextensionmodule.proxies.Resource_6 getRevision_Resource_6() throws com.mendix.core.CoreException
	{
		return getRevision_Resource_6(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision_Resource_6
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Resource_6 getRevision_Resource_6(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Resource_6 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Revision_Resource_6.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Resource_6.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Revision_Resource_6
	 * @param revision_resource_6
	 */
	public final void setRevision_Resource_6(azureextensionmodule.proxies.Resource_6 revision_resource_6)
	{
		setRevision_Resource_6(getContext(), revision_resource_6);
	}

	/**
	 * Set value of Revision_Resource_6
	 * @param context
	 * @param revision_resource_6
	 */
	public final void setRevision_Resource_6(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Resource_6 revision_resource_6)
	{
		if (revision_resource_6 == null) {
			getMendixObject().setValue(context, MemberNames.Revision_Resource_6.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Revision_Resource_6.toString(), revision_resource_6.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return revisionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final azureextensionmodule.proxies.Revision that = (azureextensionmodule.proxies.Revision) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
