// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package azureextensionmodule.proxies;

public class Root
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AzureExtensionModule.Root";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		System_AreaPath("System_AreaPath"),
		System_TeamProject("System_TeamProject"),
		System_IterationPath("System_IterationPath"),
		System_WorkItemType("System_WorkItemType"),
		System_State("System_State"),
		System_Reason("System_Reason"),
		System_CreatedDate("System_CreatedDate"),
		System_ChangedDate("System_ChangedDate"),
		System_Title("System_Title"),
		Microsoft_VSTS_Common_Severity("Microsoft_VSTS_Common_Severity"),
		WEF_EB329F44FE5F4A94ACB1DA153FDF38BA_Kanban_Column("WEF_EB329F44FE5F4A94ACB1DA153FDF38BA_Kanban_Column"),
		Token_type("Token_type"),
		Expires_in("Expires_in"),
		Not_before("Not_before"),
		Expires_on("Expires_on"),
		Resource("Resource"),
		Access_token("Access_token"),
		SubscriptionId("SubscriptionId"),
		NotificationId("NotificationId"),
		_id("_id"),
		EventType("EventType"),
		PublisherId("PublisherId"),
		ResourceVersion("ResourceVersion"),
		_createdDate("_createdDate"),
		Custom_Valuestream("Custom_Valuestream"),
		Count("Count"),
		Custom_ValuestreamID("Custom_ValuestreamID"),
		message("AzureExtensionModule.message"),
		detailedMessage("AzureExtensionModule.detailedMessage"),
		ResourceContainers_Root("AzureExtensionModule.ResourceContainers_Root"),
		Message_5_Root("AzureExtensionModule.Message_5_Root"),
		DetailedMessage_2_Root("AzureExtensionModule.DetailedMessage_2_Root"),
		Resource_2_Root("AzureExtensionModule.Resource_2_Root"),
		Message_6_Root("AzureExtensionModule.Message_6_Root"),
		DetailedMessage_3_Root("AzureExtensionModule.DetailedMessage_3_Root"),
		Resource_4_Root("AzureExtensionModule.Resource_4_Root"),
		Message_9_Root("AzureExtensionModule.Message_9_Root"),
		DetailedMessage_6_Root("AzureExtensionModule.DetailedMessage_6_Root"),
		Resource_6_Root("AzureExtensionModule.Resource_6_Root"),
		DetailedMessage_7_Root("AzureExtensionModule.DetailedMessage_7_Root"),
		Resource_7_Root("AzureExtensionModule.Resource_7_Root"),
		Value_Root("AzureExtensionModule.Value_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Root(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Root(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject)
	{
		if (rootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, rootMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.rootMendixObject = rootMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Root.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static azureextensionmodule.proxies.Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return azureextensionmodule.proxies.Root.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static azureextensionmodule.proxies.Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new azureextensionmodule.proxies.Root(context, mendixObject);
	}

	public static azureextensionmodule.proxies.Root load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return azureextensionmodule.proxies.Root.initialize(context, mendixObject);
	}

	public static java.util.List<azureextensionmodule.proxies.Root> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> azureextensionmodule.proxies.Root.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of System_AreaPath
	 */
	public final java.lang.String getSystem_AreaPath()
	{
		return getSystem_AreaPath(getContext());
	}

	/**
	 * @param context
	 * @return value of System_AreaPath
	 */
	public final java.lang.String getSystem_AreaPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.System_AreaPath.toString());
	}

	/**
	 * Set value of System_AreaPath
	 * @param system_areapath
	 */
	public final void setSystem_AreaPath(java.lang.String system_areapath)
	{
		setSystem_AreaPath(getContext(), system_areapath);
	}

	/**
	 * Set value of System_AreaPath
	 * @param context
	 * @param system_areapath
	 */
	public final void setSystem_AreaPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String system_areapath)
	{
		getMendixObject().setValue(context, MemberNames.System_AreaPath.toString(), system_areapath);
	}

	/**
	 * @return value of System_TeamProject
	 */
	public final java.lang.String getSystem_TeamProject()
	{
		return getSystem_TeamProject(getContext());
	}

	/**
	 * @param context
	 * @return value of System_TeamProject
	 */
	public final java.lang.String getSystem_TeamProject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.System_TeamProject.toString());
	}

	/**
	 * Set value of System_TeamProject
	 * @param system_teamproject
	 */
	public final void setSystem_TeamProject(java.lang.String system_teamproject)
	{
		setSystem_TeamProject(getContext(), system_teamproject);
	}

	/**
	 * Set value of System_TeamProject
	 * @param context
	 * @param system_teamproject
	 */
	public final void setSystem_TeamProject(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String system_teamproject)
	{
		getMendixObject().setValue(context, MemberNames.System_TeamProject.toString(), system_teamproject);
	}

	/**
	 * @return value of System_IterationPath
	 */
	public final java.lang.String getSystem_IterationPath()
	{
		return getSystem_IterationPath(getContext());
	}

	/**
	 * @param context
	 * @return value of System_IterationPath
	 */
	public final java.lang.String getSystem_IterationPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.System_IterationPath.toString());
	}

	/**
	 * Set value of System_IterationPath
	 * @param system_iterationpath
	 */
	public final void setSystem_IterationPath(java.lang.String system_iterationpath)
	{
		setSystem_IterationPath(getContext(), system_iterationpath);
	}

	/**
	 * Set value of System_IterationPath
	 * @param context
	 * @param system_iterationpath
	 */
	public final void setSystem_IterationPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String system_iterationpath)
	{
		getMendixObject().setValue(context, MemberNames.System_IterationPath.toString(), system_iterationpath);
	}

	/**
	 * @return value of System_WorkItemType
	 */
	public final java.lang.String getSystem_WorkItemType()
	{
		return getSystem_WorkItemType(getContext());
	}

	/**
	 * @param context
	 * @return value of System_WorkItemType
	 */
	public final java.lang.String getSystem_WorkItemType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.System_WorkItemType.toString());
	}

	/**
	 * Set value of System_WorkItemType
	 * @param system_workitemtype
	 */
	public final void setSystem_WorkItemType(java.lang.String system_workitemtype)
	{
		setSystem_WorkItemType(getContext(), system_workitemtype);
	}

	/**
	 * Set value of System_WorkItemType
	 * @param context
	 * @param system_workitemtype
	 */
	public final void setSystem_WorkItemType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String system_workitemtype)
	{
		getMendixObject().setValue(context, MemberNames.System_WorkItemType.toString(), system_workitemtype);
	}

	/**
	 * @return value of System_State
	 */
	public final java.lang.String getSystem_State()
	{
		return getSystem_State(getContext());
	}

	/**
	 * @param context
	 * @return value of System_State
	 */
	public final java.lang.String getSystem_State(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.System_State.toString());
	}

	/**
	 * Set value of System_State
	 * @param system_state
	 */
	public final void setSystem_State(java.lang.String system_state)
	{
		setSystem_State(getContext(), system_state);
	}

	/**
	 * Set value of System_State
	 * @param context
	 * @param system_state
	 */
	public final void setSystem_State(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String system_state)
	{
		getMendixObject().setValue(context, MemberNames.System_State.toString(), system_state);
	}

	/**
	 * @return value of System_Reason
	 */
	public final java.lang.String getSystem_Reason()
	{
		return getSystem_Reason(getContext());
	}

	/**
	 * @param context
	 * @return value of System_Reason
	 */
	public final java.lang.String getSystem_Reason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.System_Reason.toString());
	}

	/**
	 * Set value of System_Reason
	 * @param system_reason
	 */
	public final void setSystem_Reason(java.lang.String system_reason)
	{
		setSystem_Reason(getContext(), system_reason);
	}

	/**
	 * Set value of System_Reason
	 * @param context
	 * @param system_reason
	 */
	public final void setSystem_Reason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String system_reason)
	{
		getMendixObject().setValue(context, MemberNames.System_Reason.toString(), system_reason);
	}

	/**
	 * @return value of System_CreatedDate
	 */
	public final java.util.Date getSystem_CreatedDate()
	{
		return getSystem_CreatedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of System_CreatedDate
	 */
	public final java.util.Date getSystem_CreatedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.System_CreatedDate.toString());
	}

	/**
	 * Set value of System_CreatedDate
	 * @param system_createddate
	 */
	public final void setSystem_CreatedDate(java.util.Date system_createddate)
	{
		setSystem_CreatedDate(getContext(), system_createddate);
	}

	/**
	 * Set value of System_CreatedDate
	 * @param context
	 * @param system_createddate
	 */
	public final void setSystem_CreatedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date system_createddate)
	{
		getMendixObject().setValue(context, MemberNames.System_CreatedDate.toString(), system_createddate);
	}

	/**
	 * @return value of System_ChangedDate
	 */
	public final java.util.Date getSystem_ChangedDate()
	{
		return getSystem_ChangedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of System_ChangedDate
	 */
	public final java.util.Date getSystem_ChangedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.System_ChangedDate.toString());
	}

	/**
	 * Set value of System_ChangedDate
	 * @param system_changeddate
	 */
	public final void setSystem_ChangedDate(java.util.Date system_changeddate)
	{
		setSystem_ChangedDate(getContext(), system_changeddate);
	}

	/**
	 * Set value of System_ChangedDate
	 * @param context
	 * @param system_changeddate
	 */
	public final void setSystem_ChangedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date system_changeddate)
	{
		getMendixObject().setValue(context, MemberNames.System_ChangedDate.toString(), system_changeddate);
	}

	/**
	 * @return value of System_Title
	 */
	public final java.lang.String getSystem_Title()
	{
		return getSystem_Title(getContext());
	}

	/**
	 * @param context
	 * @return value of System_Title
	 */
	public final java.lang.String getSystem_Title(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.System_Title.toString());
	}

	/**
	 * Set value of System_Title
	 * @param system_title
	 */
	public final void setSystem_Title(java.lang.String system_title)
	{
		setSystem_Title(getContext(), system_title);
	}

	/**
	 * Set value of System_Title
	 * @param context
	 * @param system_title
	 */
	public final void setSystem_Title(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String system_title)
	{
		getMendixObject().setValue(context, MemberNames.System_Title.toString(), system_title);
	}

	/**
	 * @return value of Microsoft_VSTS_Common_Severity
	 */
	public final java.lang.String getMicrosoft_VSTS_Common_Severity()
	{
		return getMicrosoft_VSTS_Common_Severity(getContext());
	}

	/**
	 * @param context
	 * @return value of Microsoft_VSTS_Common_Severity
	 */
	public final java.lang.String getMicrosoft_VSTS_Common_Severity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Microsoft_VSTS_Common_Severity.toString());
	}

	/**
	 * Set value of Microsoft_VSTS_Common_Severity
	 * @param microsoft_vsts_common_severity
	 */
	public final void setMicrosoft_VSTS_Common_Severity(java.lang.String microsoft_vsts_common_severity)
	{
		setMicrosoft_VSTS_Common_Severity(getContext(), microsoft_vsts_common_severity);
	}

	/**
	 * Set value of Microsoft_VSTS_Common_Severity
	 * @param context
	 * @param microsoft_vsts_common_severity
	 */
	public final void setMicrosoft_VSTS_Common_Severity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String microsoft_vsts_common_severity)
	{
		getMendixObject().setValue(context, MemberNames.Microsoft_VSTS_Common_Severity.toString(), microsoft_vsts_common_severity);
	}

	/**
	 * @return value of WEF_EB329F44FE5F4A94ACB1DA153FDF38BA_Kanban_Column
	 */
	public final java.lang.String getWEF_EB329F44FE5F4A94ACB1DA153FDF38BA_Kanban_Column()
	{
		return getWEF_EB329F44FE5F4A94ACB1DA153FDF38BA_Kanban_Column(getContext());
	}

	/**
	 * @param context
	 * @return value of WEF_EB329F44FE5F4A94ACB1DA153FDF38BA_Kanban_Column
	 */
	public final java.lang.String getWEF_EB329F44FE5F4A94ACB1DA153FDF38BA_Kanban_Column(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WEF_EB329F44FE5F4A94ACB1DA153FDF38BA_Kanban_Column.toString());
	}

	/**
	 * Set value of WEF_EB329F44FE5F4A94ACB1DA153FDF38BA_Kanban_Column
	 * @param wef_eb329f44fe5f4a94acb1da153fdf38ba_kanban_column
	 */
	public final void setWEF_EB329F44FE5F4A94ACB1DA153FDF38BA_Kanban_Column(java.lang.String wef_eb329f44fe5f4a94acb1da153fdf38ba_kanban_column)
	{
		setWEF_EB329F44FE5F4A94ACB1DA153FDF38BA_Kanban_Column(getContext(), wef_eb329f44fe5f4a94acb1da153fdf38ba_kanban_column);
	}

	/**
	 * Set value of WEF_EB329F44FE5F4A94ACB1DA153FDF38BA_Kanban_Column
	 * @param context
	 * @param wef_eb329f44fe5f4a94acb1da153fdf38ba_kanban_column
	 */
	public final void setWEF_EB329F44FE5F4A94ACB1DA153FDF38BA_Kanban_Column(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String wef_eb329f44fe5f4a94acb1da153fdf38ba_kanban_column)
	{
		getMendixObject().setValue(context, MemberNames.WEF_EB329F44FE5F4A94ACB1DA153FDF38BA_Kanban_Column.toString(), wef_eb329f44fe5f4a94acb1da153fdf38ba_kanban_column);
	}

	/**
	 * @return value of Token_type
	 */
	public final java.lang.String getToken_type()
	{
		return getToken_type(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_type
	 */
	public final java.lang.String getToken_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Token_type.toString());
	}

	/**
	 * Set value of Token_type
	 * @param token_type
	 */
	public final void setToken_type(java.lang.String token_type)
	{
		setToken_type(getContext(), token_type);
	}

	/**
	 * Set value of Token_type
	 * @param context
	 * @param token_type
	 */
	public final void setToken_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token_type)
	{
		getMendixObject().setValue(context, MemberNames.Token_type.toString(), token_type);
	}

	/**
	 * @return value of Expires_in
	 */
	public final java.lang.String getExpires_in()
	{
		return getExpires_in(getContext());
	}

	/**
	 * @param context
	 * @return value of Expires_in
	 */
	public final java.lang.String getExpires_in(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Expires_in.toString());
	}

	/**
	 * Set value of Expires_in
	 * @param expires_in
	 */
	public final void setExpires_in(java.lang.String expires_in)
	{
		setExpires_in(getContext(), expires_in);
	}

	/**
	 * Set value of Expires_in
	 * @param context
	 * @param expires_in
	 */
	public final void setExpires_in(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String expires_in)
	{
		getMendixObject().setValue(context, MemberNames.Expires_in.toString(), expires_in);
	}

	/**
	 * @return value of Not_before
	 */
	public final java.lang.String getNot_before()
	{
		return getNot_before(getContext());
	}

	/**
	 * @param context
	 * @return value of Not_before
	 */
	public final java.lang.String getNot_before(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Not_before.toString());
	}

	/**
	 * Set value of Not_before
	 * @param not_before
	 */
	public final void setNot_before(java.lang.String not_before)
	{
		setNot_before(getContext(), not_before);
	}

	/**
	 * Set value of Not_before
	 * @param context
	 * @param not_before
	 */
	public final void setNot_before(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String not_before)
	{
		getMendixObject().setValue(context, MemberNames.Not_before.toString(), not_before);
	}

	/**
	 * @return value of Expires_on
	 */
	public final java.lang.String getExpires_on()
	{
		return getExpires_on(getContext());
	}

	/**
	 * @param context
	 * @return value of Expires_on
	 */
	public final java.lang.String getExpires_on(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Expires_on.toString());
	}

	/**
	 * Set value of Expires_on
	 * @param expires_on
	 */
	public final void setExpires_on(java.lang.String expires_on)
	{
		setExpires_on(getContext(), expires_on);
	}

	/**
	 * Set value of Expires_on
	 * @param context
	 * @param expires_on
	 */
	public final void setExpires_on(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String expires_on)
	{
		getMendixObject().setValue(context, MemberNames.Expires_on.toString(), expires_on);
	}

	/**
	 * @return value of Resource
	 */
	public final java.lang.String getResource()
	{
		return getResource(getContext());
	}

	/**
	 * @param context
	 * @return value of Resource
	 */
	public final java.lang.String getResource(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Resource.toString());
	}

	/**
	 * Set value of Resource
	 * @param resource
	 */
	public final void setResource(java.lang.String resource)
	{
		setResource(getContext(), resource);
	}

	/**
	 * Set value of Resource
	 * @param context
	 * @param resource
	 */
	public final void setResource(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String resource)
	{
		getMendixObject().setValue(context, MemberNames.Resource.toString(), resource);
	}

	/**
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token()
	{
		return getAccess_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Access_token.toString());
	}

	/**
	 * Set value of Access_token
	 * @param access_token
	 */
	public final void setAccess_token(java.lang.String access_token)
	{
		setAccess_token(getContext(), access_token);
	}

	/**
	 * Set value of Access_token
	 * @param context
	 * @param access_token
	 */
	public final void setAccess_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String access_token)
	{
		getMendixObject().setValue(context, MemberNames.Access_token.toString(), access_token);
	}

	/**
	 * @return value of SubscriptionId
	 */
	public final java.lang.String getSubscriptionId()
	{
		return getSubscriptionId(getContext());
	}

	/**
	 * @param context
	 * @return value of SubscriptionId
	 */
	public final java.lang.String getSubscriptionId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubscriptionId.toString());
	}

	/**
	 * Set value of SubscriptionId
	 * @param subscriptionid
	 */
	public final void setSubscriptionId(java.lang.String subscriptionid)
	{
		setSubscriptionId(getContext(), subscriptionid);
	}

	/**
	 * Set value of SubscriptionId
	 * @param context
	 * @param subscriptionid
	 */
	public final void setSubscriptionId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subscriptionid)
	{
		getMendixObject().setValue(context, MemberNames.SubscriptionId.toString(), subscriptionid);
	}

	/**
	 * @return value of NotificationId
	 */
	public final java.lang.Integer getNotificationId()
	{
		return getNotificationId(getContext());
	}

	/**
	 * @param context
	 * @return value of NotificationId
	 */
	public final java.lang.Integer getNotificationId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NotificationId.toString());
	}

	/**
	 * Set value of NotificationId
	 * @param notificationid
	 */
	public final void setNotificationId(java.lang.Integer notificationid)
	{
		setNotificationId(getContext(), notificationid);
	}

	/**
	 * Set value of NotificationId
	 * @param context
	 * @param notificationid
	 */
	public final void setNotificationId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer notificationid)
	{
		getMendixObject().setValue(context, MemberNames.NotificationId.toString(), notificationid);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of EventType
	 */
	public final java.lang.String getEventType()
	{
		return getEventType(getContext());
	}

	/**
	 * @param context
	 * @return value of EventType
	 */
	public final java.lang.String getEventType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EventType.toString());
	}

	/**
	 * Set value of EventType
	 * @param eventtype
	 */
	public final void setEventType(java.lang.String eventtype)
	{
		setEventType(getContext(), eventtype);
	}

	/**
	 * Set value of EventType
	 * @param context
	 * @param eventtype
	 */
	public final void setEventType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String eventtype)
	{
		getMendixObject().setValue(context, MemberNames.EventType.toString(), eventtype);
	}

	/**
	 * @return value of PublisherId
	 */
	public final java.lang.String getPublisherId()
	{
		return getPublisherId(getContext());
	}

	/**
	 * @param context
	 * @return value of PublisherId
	 */
	public final java.lang.String getPublisherId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PublisherId.toString());
	}

	/**
	 * Set value of PublisherId
	 * @param publisherid
	 */
	public final void setPublisherId(java.lang.String publisherid)
	{
		setPublisherId(getContext(), publisherid);
	}

	/**
	 * Set value of PublisherId
	 * @param context
	 * @param publisherid
	 */
	public final void setPublisherId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String publisherid)
	{
		getMendixObject().setValue(context, MemberNames.PublisherId.toString(), publisherid);
	}

	/**
	 * @return value of ResourceVersion
	 */
	public final java.lang.String getResourceVersion()
	{
		return getResourceVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceVersion
	 */
	public final java.lang.String getResourceVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResourceVersion.toString());
	}

	/**
	 * Set value of ResourceVersion
	 * @param resourceversion
	 */
	public final void setResourceVersion(java.lang.String resourceversion)
	{
		setResourceVersion(getContext(), resourceversion);
	}

	/**
	 * Set value of ResourceVersion
	 * @param context
	 * @param resourceversion
	 */
	public final void setResourceVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String resourceversion)
	{
		getMendixObject().setValue(context, MemberNames.ResourceVersion.toString(), resourceversion);
	}

	/**
	 * @return value of _createdDate
	 */
	public final java.util.Date get_createdDate()
	{
		return get_createdDate(getContext());
	}

	/**
	 * @param context
	 * @return value of _createdDate
	 */
	public final java.util.Date get_createdDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames._createdDate.toString());
	}

	/**
	 * Set value of _createdDate
	 * @param _createddate
	 */
	public final void set_createdDate(java.util.Date _createddate)
	{
		set_createdDate(getContext(), _createddate);
	}

	/**
	 * Set value of _createdDate
	 * @param context
	 * @param _createddate
	 */
	public final void set_createdDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date _createddate)
	{
		getMendixObject().setValue(context, MemberNames._createdDate.toString(), _createddate);
	}

	/**
	 * @return value of Custom_Valuestream
	 */
	public final java.lang.String getCustom_Valuestream()
	{
		return getCustom_Valuestream(getContext());
	}

	/**
	 * @param context
	 * @return value of Custom_Valuestream
	 */
	public final java.lang.String getCustom_Valuestream(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Custom_Valuestream.toString());
	}

	/**
	 * Set value of Custom_Valuestream
	 * @param custom_valuestream
	 */
	public final void setCustom_Valuestream(java.lang.String custom_valuestream)
	{
		setCustom_Valuestream(getContext(), custom_valuestream);
	}

	/**
	 * Set value of Custom_Valuestream
	 * @param context
	 * @param custom_valuestream
	 */
	public final void setCustom_Valuestream(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String custom_valuestream)
	{
		getMendixObject().setValue(context, MemberNames.Custom_Valuestream.toString(), custom_valuestream);
	}

	/**
	 * @return value of Count
	 */
	public final java.lang.Integer getCount()
	{
		return getCount(getContext());
	}

	/**
	 * @param context
	 * @return value of Count
	 */
	public final java.lang.Integer getCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Count.toString());
	}

	/**
	 * Set value of Count
	 * @param count
	 */
	public final void setCount(java.lang.Integer count)
	{
		setCount(getContext(), count);
	}

	/**
	 * Set value of Count
	 * @param context
	 * @param count
	 */
	public final void setCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer count)
	{
		getMendixObject().setValue(context, MemberNames.Count.toString(), count);
	}

	/**
	 * @return value of Custom_ValuestreamID
	 */
	public final java.lang.Integer getCustom_ValuestreamID()
	{
		return getCustom_ValuestreamID(getContext());
	}

	/**
	 * @param context
	 * @return value of Custom_ValuestreamID
	 */
	public final java.lang.Integer getCustom_ValuestreamID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Custom_ValuestreamID.toString());
	}

	/**
	 * Set value of Custom_ValuestreamID
	 * @param custom_valuestreamid
	 */
	public final void setCustom_ValuestreamID(java.lang.Integer custom_valuestreamid)
	{
		setCustom_ValuestreamID(getContext(), custom_valuestreamid);
	}

	/**
	 * Set value of Custom_ValuestreamID
	 * @param context
	 * @param custom_valuestreamid
	 */
	public final void setCustom_ValuestreamID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer custom_valuestreamid)
	{
		getMendixObject().setValue(context, MemberNames.Custom_ValuestreamID.toString(), custom_valuestreamid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of message
	 */
	public final azureextensionmodule.proxies.Message_Root getmessage() throws com.mendix.core.CoreException
	{
		return getmessage(getContext());
	}

	/**
	 * @param context
	 * @return value of message
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Message_Root getmessage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Message_Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.message.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Message_Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of message
	 * @param message
	 */
	public final void setmessage(azureextensionmodule.proxies.Message_Root message)
	{
		setmessage(getContext(), message);
	}

	/**
	 * Set value of message
	 * @param context
	 * @param message
	 */
	public final void setmessage(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Message_Root message)
	{
		if (message == null) {
			getMendixObject().setValue(context, MemberNames.message.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.message.toString(), message.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of detailedMessage
	 */
	public final azureextensionmodule.proxies.Detailed_Message getdetailedMessage() throws com.mendix.core.CoreException
	{
		return getdetailedMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of detailedMessage
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Detailed_Message getdetailedMessage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Detailed_Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.detailedMessage.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Detailed_Message.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of detailedMessage
	 * @param detailedmessage
	 */
	public final void setdetailedMessage(azureextensionmodule.proxies.Detailed_Message detailedmessage)
	{
		setdetailedMessage(getContext(), detailedmessage);
	}

	/**
	 * Set value of detailedMessage
	 * @param context
	 * @param detailedmessage
	 */
	public final void setdetailedMessage(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Detailed_Message detailedmessage)
	{
		if (detailedmessage == null) {
			getMendixObject().setValue(context, MemberNames.detailedMessage.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.detailedMessage.toString(), detailedmessage.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResourceContainers_Root
	 */
	public final azureextensionmodule.proxies.ResourceContainers getResourceContainers_Root() throws com.mendix.core.CoreException
	{
		return getResourceContainers_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceContainers_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.ResourceContainers getResourceContainers_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.ResourceContainers result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResourceContainers_Root.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.ResourceContainers.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResourceContainers_Root
	 * @param resourcecontainers_root
	 */
	public final void setResourceContainers_Root(azureextensionmodule.proxies.ResourceContainers resourcecontainers_root)
	{
		setResourceContainers_Root(getContext(), resourcecontainers_root);
	}

	/**
	 * Set value of ResourceContainers_Root
	 * @param context
	 * @param resourcecontainers_root
	 */
	public final void setResourceContainers_Root(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.ResourceContainers resourcecontainers_root)
	{
		if (resourcecontainers_root == null) {
			getMendixObject().setValue(context, MemberNames.ResourceContainers_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResourceContainers_Root.toString(), resourcecontainers_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Message_5_Root
	 */
	public final azureextensionmodule.proxies.Message_5 getMessage_5_Root() throws com.mendix.core.CoreException
	{
		return getMessage_5_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Message_5_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Message_5 getMessage_5_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Message_5 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Message_5_Root.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Message_5.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Message_5_Root
	 * @param message_5_root
	 */
	public final void setMessage_5_Root(azureextensionmodule.proxies.Message_5 message_5_root)
	{
		setMessage_5_Root(getContext(), message_5_root);
	}

	/**
	 * Set value of Message_5_Root
	 * @param context
	 * @param message_5_root
	 */
	public final void setMessage_5_Root(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Message_5 message_5_root)
	{
		if (message_5_root == null) {
			getMendixObject().setValue(context, MemberNames.Message_5_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Message_5_Root.toString(), message_5_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DetailedMessage_2_Root
	 */
	public final azureextensionmodule.proxies.DetailedMessage_2 getDetailedMessage_2_Root() throws com.mendix.core.CoreException
	{
		return getDetailedMessage_2_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of DetailedMessage_2_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.DetailedMessage_2 getDetailedMessage_2_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.DetailedMessage_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DetailedMessage_2_Root.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.DetailedMessage_2.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DetailedMessage_2_Root
	 * @param detailedmessage_2_root
	 */
	public final void setDetailedMessage_2_Root(azureextensionmodule.proxies.DetailedMessage_2 detailedmessage_2_root)
	{
		setDetailedMessage_2_Root(getContext(), detailedmessage_2_root);
	}

	/**
	 * Set value of DetailedMessage_2_Root
	 * @param context
	 * @param detailedmessage_2_root
	 */
	public final void setDetailedMessage_2_Root(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.DetailedMessage_2 detailedmessage_2_root)
	{
		if (detailedmessage_2_root == null) {
			getMendixObject().setValue(context, MemberNames.DetailedMessage_2_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DetailedMessage_2_Root.toString(), detailedmessage_2_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Resource_2_Root
	 */
	public final azureextensionmodule.proxies.Resource_2 getResource_2_Root() throws com.mendix.core.CoreException
	{
		return getResource_2_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Resource_2_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Resource_2 getResource_2_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Resource_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Resource_2_Root.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Resource_2.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Resource_2_Root
	 * @param resource_2_root
	 */
	public final void setResource_2_Root(azureextensionmodule.proxies.Resource_2 resource_2_root)
	{
		setResource_2_Root(getContext(), resource_2_root);
	}

	/**
	 * Set value of Resource_2_Root
	 * @param context
	 * @param resource_2_root
	 */
	public final void setResource_2_Root(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Resource_2 resource_2_root)
	{
		if (resource_2_root == null) {
			getMendixObject().setValue(context, MemberNames.Resource_2_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Resource_2_Root.toString(), resource_2_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Message_6_Root
	 */
	public final azureextensionmodule.proxies.Message_6 getMessage_6_Root() throws com.mendix.core.CoreException
	{
		return getMessage_6_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Message_6_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Message_6 getMessage_6_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Message_6 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Message_6_Root.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Message_6.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Message_6_Root
	 * @param message_6_root
	 */
	public final void setMessage_6_Root(azureextensionmodule.proxies.Message_6 message_6_root)
	{
		setMessage_6_Root(getContext(), message_6_root);
	}

	/**
	 * Set value of Message_6_Root
	 * @param context
	 * @param message_6_root
	 */
	public final void setMessage_6_Root(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Message_6 message_6_root)
	{
		if (message_6_root == null) {
			getMendixObject().setValue(context, MemberNames.Message_6_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Message_6_Root.toString(), message_6_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DetailedMessage_3_Root
	 */
	public final azureextensionmodule.proxies.DetailedMessage_3 getDetailedMessage_3_Root() throws com.mendix.core.CoreException
	{
		return getDetailedMessage_3_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of DetailedMessage_3_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.DetailedMessage_3 getDetailedMessage_3_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.DetailedMessage_3 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DetailedMessage_3_Root.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.DetailedMessage_3.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DetailedMessage_3_Root
	 * @param detailedmessage_3_root
	 */
	public final void setDetailedMessage_3_Root(azureextensionmodule.proxies.DetailedMessage_3 detailedmessage_3_root)
	{
		setDetailedMessage_3_Root(getContext(), detailedmessage_3_root);
	}

	/**
	 * Set value of DetailedMessage_3_Root
	 * @param context
	 * @param detailedmessage_3_root
	 */
	public final void setDetailedMessage_3_Root(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.DetailedMessage_3 detailedmessage_3_root)
	{
		if (detailedmessage_3_root == null) {
			getMendixObject().setValue(context, MemberNames.DetailedMessage_3_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DetailedMessage_3_Root.toString(), detailedmessage_3_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Resource_4_Root
	 */
	public final azureextensionmodule.proxies.Resource_4 getResource_4_Root() throws com.mendix.core.CoreException
	{
		return getResource_4_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Resource_4_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Resource_4 getResource_4_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Resource_4 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Resource_4_Root.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Resource_4.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Resource_4_Root
	 * @param resource_4_root
	 */
	public final void setResource_4_Root(azureextensionmodule.proxies.Resource_4 resource_4_root)
	{
		setResource_4_Root(getContext(), resource_4_root);
	}

	/**
	 * Set value of Resource_4_Root
	 * @param context
	 * @param resource_4_root
	 */
	public final void setResource_4_Root(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Resource_4 resource_4_root)
	{
		if (resource_4_root == null) {
			getMendixObject().setValue(context, MemberNames.Resource_4_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Resource_4_Root.toString(), resource_4_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Message_9_Root
	 */
	public final azureextensionmodule.proxies.Message_9 getMessage_9_Root() throws com.mendix.core.CoreException
	{
		return getMessage_9_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Message_9_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Message_9 getMessage_9_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Message_9 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Message_9_Root.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Message_9.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Message_9_Root
	 * @param message_9_root
	 */
	public final void setMessage_9_Root(azureextensionmodule.proxies.Message_9 message_9_root)
	{
		setMessage_9_Root(getContext(), message_9_root);
	}

	/**
	 * Set value of Message_9_Root
	 * @param context
	 * @param message_9_root
	 */
	public final void setMessage_9_Root(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Message_9 message_9_root)
	{
		if (message_9_root == null) {
			getMendixObject().setValue(context, MemberNames.Message_9_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Message_9_Root.toString(), message_9_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DetailedMessage_6_Root
	 */
	public final azureextensionmodule.proxies.DetailedMessage_6 getDetailedMessage_6_Root() throws com.mendix.core.CoreException
	{
		return getDetailedMessage_6_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of DetailedMessage_6_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.DetailedMessage_6 getDetailedMessage_6_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.DetailedMessage_6 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DetailedMessage_6_Root.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.DetailedMessage_6.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DetailedMessage_6_Root
	 * @param detailedmessage_6_root
	 */
	public final void setDetailedMessage_6_Root(azureextensionmodule.proxies.DetailedMessage_6 detailedmessage_6_root)
	{
		setDetailedMessage_6_Root(getContext(), detailedmessage_6_root);
	}

	/**
	 * Set value of DetailedMessage_6_Root
	 * @param context
	 * @param detailedmessage_6_root
	 */
	public final void setDetailedMessage_6_Root(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.DetailedMessage_6 detailedmessage_6_root)
	{
		if (detailedmessage_6_root == null) {
			getMendixObject().setValue(context, MemberNames.DetailedMessage_6_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DetailedMessage_6_Root.toString(), detailedmessage_6_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Resource_6_Root
	 */
	public final azureextensionmodule.proxies.Resource_6 getResource_6_Root() throws com.mendix.core.CoreException
	{
		return getResource_6_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Resource_6_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Resource_6 getResource_6_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Resource_6 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Resource_6_Root.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Resource_6.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Resource_6_Root
	 * @param resource_6_root
	 */
	public final void setResource_6_Root(azureextensionmodule.proxies.Resource_6 resource_6_root)
	{
		setResource_6_Root(getContext(), resource_6_root);
	}

	/**
	 * Set value of Resource_6_Root
	 * @param context
	 * @param resource_6_root
	 */
	public final void setResource_6_Root(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Resource_6 resource_6_root)
	{
		if (resource_6_root == null) {
			getMendixObject().setValue(context, MemberNames.Resource_6_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Resource_6_Root.toString(), resource_6_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DetailedMessage_7_Root
	 */
	public final azureextensionmodule.proxies.DetailedMessage_7 getDetailedMessage_7_Root() throws com.mendix.core.CoreException
	{
		return getDetailedMessage_7_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of DetailedMessage_7_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.DetailedMessage_7 getDetailedMessage_7_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.DetailedMessage_7 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DetailedMessage_7_Root.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.DetailedMessage_7.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DetailedMessage_7_Root
	 * @param detailedmessage_7_root
	 */
	public final void setDetailedMessage_7_Root(azureextensionmodule.proxies.DetailedMessage_7 detailedmessage_7_root)
	{
		setDetailedMessage_7_Root(getContext(), detailedmessage_7_root);
	}

	/**
	 * Set value of DetailedMessage_7_Root
	 * @param context
	 * @param detailedmessage_7_root
	 */
	public final void setDetailedMessage_7_Root(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.DetailedMessage_7 detailedmessage_7_root)
	{
		if (detailedmessage_7_root == null) {
			getMendixObject().setValue(context, MemberNames.DetailedMessage_7_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DetailedMessage_7_Root.toString(), detailedmessage_7_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Resource_7_Root
	 */
	public final azureextensionmodule.proxies.Resource_7 getResource_7_Root() throws com.mendix.core.CoreException
	{
		return getResource_7_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Resource_7_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Resource_7 getResource_7_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Resource_7 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Resource_7_Root.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Resource_7.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Resource_7_Root
	 * @param resource_7_root
	 */
	public final void setResource_7_Root(azureextensionmodule.proxies.Resource_7 resource_7_root)
	{
		setResource_7_Root(getContext(), resource_7_root);
	}

	/**
	 * Set value of Resource_7_Root
	 * @param context
	 * @param resource_7_root
	 */
	public final void setResource_7_Root(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Resource_7 resource_7_root)
	{
		if (resource_7_root == null) {
			getMendixObject().setValue(context, MemberNames.Resource_7_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Resource_7_Root.toString(), resource_7_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Value_Root
	 */
	public final azureextensionmodule.proxies.Value getValue_Root() throws com.mendix.core.CoreException
	{
		return getValue_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Value_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Value getValue_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Value result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Value_Root.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Value.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Value_Root
	 * @param value_root
	 */
	public final void setValue_Root(azureextensionmodule.proxies.Value value_root)
	{
		setValue_Root(getContext(), value_root);
	}

	/**
	 * Set value of Value_Root
	 * @param context
	 * @param value_root
	 */
	public final void setValue_Root(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Value value_root)
	{
		if (value_root == null) {
			getMendixObject().setValue(context, MemberNames.Value_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Value_Root.toString(), value_root.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rootMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final azureextensionmodule.proxies.Root that = (azureextensionmodule.proxies.Root) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
