// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package azureextensionmodule.proxies;

public class System_AuthorizedDate
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject system_AuthorizedDateMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AzureExtensionModule.System_AuthorizedDate";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OldValue("OldValue"),
		NewValue("NewValue"),
		System_AuthorizedDate_Fields_6("AzureExtensionModule.System_AuthorizedDate_Fields_6"),
		System_AuthorizedDate_Fields_7("AzureExtensionModule.System_AuthorizedDate_Fields_7"),
		System_AuthorizedDate_Fields_8("AzureExtensionModule.System_AuthorizedDate_Fields_8");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public System_AuthorizedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected System_AuthorizedDate(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject system_AuthorizedDateMendixObject)
	{
		if (system_AuthorizedDateMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, system_AuthorizedDateMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.system_AuthorizedDateMendixObject = system_AuthorizedDateMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'System_AuthorizedDate.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static azureextensionmodule.proxies.System_AuthorizedDate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return azureextensionmodule.proxies.System_AuthorizedDate.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static azureextensionmodule.proxies.System_AuthorizedDate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new azureextensionmodule.proxies.System_AuthorizedDate(context, mendixObject);
	}

	public static azureextensionmodule.proxies.System_AuthorizedDate load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return azureextensionmodule.proxies.System_AuthorizedDate.initialize(context, mendixObject);
	}

	public static java.util.List<azureextensionmodule.proxies.System_AuthorizedDate> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> azureextensionmodule.proxies.System_AuthorizedDate.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of OldValue
	 */
	public final java.util.Date getOldValue()
	{
		return getOldValue(getContext());
	}

	/**
	 * @param context
	 * @return value of OldValue
	 */
	public final java.util.Date getOldValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.OldValue.toString());
	}

	/**
	 * Set value of OldValue
	 * @param oldvalue
	 */
	public final void setOldValue(java.util.Date oldvalue)
	{
		setOldValue(getContext(), oldvalue);
	}

	/**
	 * Set value of OldValue
	 * @param context
	 * @param oldvalue
	 */
	public final void setOldValue(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date oldvalue)
	{
		getMendixObject().setValue(context, MemberNames.OldValue.toString(), oldvalue);
	}

	/**
	 * @return value of NewValue
	 */
	public final java.util.Date getNewValue()
	{
		return getNewValue(getContext());
	}

	/**
	 * @param context
	 * @return value of NewValue
	 */
	public final java.util.Date getNewValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.NewValue.toString());
	}

	/**
	 * Set value of NewValue
	 * @param newvalue
	 */
	public final void setNewValue(java.util.Date newvalue)
	{
		setNewValue(getContext(), newvalue);
	}

	/**
	 * Set value of NewValue
	 * @param context
	 * @param newvalue
	 */
	public final void setNewValue(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date newvalue)
	{
		getMendixObject().setValue(context, MemberNames.NewValue.toString(), newvalue);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of System_AuthorizedDate_Fields_6
	 */
	public final azureextensionmodule.proxies.Fields_6 getSystem_AuthorizedDate_Fields_6() throws com.mendix.core.CoreException
	{
		return getSystem_AuthorizedDate_Fields_6(getContext());
	}

	/**
	 * @param context
	 * @return value of System_AuthorizedDate_Fields_6
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Fields_6 getSystem_AuthorizedDate_Fields_6(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Fields_6 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.System_AuthorizedDate_Fields_6.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Fields_6.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of System_AuthorizedDate_Fields_6
	 * @param system_authorizeddate_fields_6
	 */
	public final void setSystem_AuthorizedDate_Fields_6(azureextensionmodule.proxies.Fields_6 system_authorizeddate_fields_6)
	{
		setSystem_AuthorizedDate_Fields_6(getContext(), system_authorizeddate_fields_6);
	}

	/**
	 * Set value of System_AuthorizedDate_Fields_6
	 * @param context
	 * @param system_authorizeddate_fields_6
	 */
	public final void setSystem_AuthorizedDate_Fields_6(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Fields_6 system_authorizeddate_fields_6)
	{
		if (system_authorizeddate_fields_6 == null) {
			getMendixObject().setValue(context, MemberNames.System_AuthorizedDate_Fields_6.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.System_AuthorizedDate_Fields_6.toString(), system_authorizeddate_fields_6.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of System_AuthorizedDate_Fields_7
	 */
	public final azureextensionmodule.proxies.Fields_7 getSystem_AuthorizedDate_Fields_7() throws com.mendix.core.CoreException
	{
		return getSystem_AuthorizedDate_Fields_7(getContext());
	}

	/**
	 * @param context
	 * @return value of System_AuthorizedDate_Fields_7
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Fields_7 getSystem_AuthorizedDate_Fields_7(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Fields_7 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.System_AuthorizedDate_Fields_7.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Fields_7.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of System_AuthorizedDate_Fields_7
	 * @param system_authorizeddate_fields_7
	 */
	public final void setSystem_AuthorizedDate_Fields_7(azureextensionmodule.proxies.Fields_7 system_authorizeddate_fields_7)
	{
		setSystem_AuthorizedDate_Fields_7(getContext(), system_authorizeddate_fields_7);
	}

	/**
	 * Set value of System_AuthorizedDate_Fields_7
	 * @param context
	 * @param system_authorizeddate_fields_7
	 */
	public final void setSystem_AuthorizedDate_Fields_7(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Fields_7 system_authorizeddate_fields_7)
	{
		if (system_authorizeddate_fields_7 == null) {
			getMendixObject().setValue(context, MemberNames.System_AuthorizedDate_Fields_7.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.System_AuthorizedDate_Fields_7.toString(), system_authorizeddate_fields_7.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of System_AuthorizedDate_Fields_8
	 */
	public final azureextensionmodule.proxies.Fields_8 getSystem_AuthorizedDate_Fields_8() throws com.mendix.core.CoreException
	{
		return getSystem_AuthorizedDate_Fields_8(getContext());
	}

	/**
	 * @param context
	 * @return value of System_AuthorizedDate_Fields_8
	 * @throws com.mendix.core.CoreException
	 */
	public final azureextensionmodule.proxies.Fields_8 getSystem_AuthorizedDate_Fields_8(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		azureextensionmodule.proxies.Fields_8 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.System_AuthorizedDate_Fields_8.toString());
		if (identifier != null) {
			result = azureextensionmodule.proxies.Fields_8.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of System_AuthorizedDate_Fields_8
	 * @param system_authorizeddate_fields_8
	 */
	public final void setSystem_AuthorizedDate_Fields_8(azureextensionmodule.proxies.Fields_8 system_authorizeddate_fields_8)
	{
		setSystem_AuthorizedDate_Fields_8(getContext(), system_authorizeddate_fields_8);
	}

	/**
	 * Set value of System_AuthorizedDate_Fields_8
	 * @param context
	 * @param system_authorizeddate_fields_8
	 */
	public final void setSystem_AuthorizedDate_Fields_8(com.mendix.systemwideinterfaces.core.IContext context, azureextensionmodule.proxies.Fields_8 system_authorizeddate_fields_8)
	{
		if (system_authorizeddate_fields_8 == null) {
			getMendixObject().setValue(context, MemberNames.System_AuthorizedDate_Fields_8.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.System_AuthorizedDate_Fields_8.toString(), system_authorizeddate_fields_8.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return system_AuthorizedDateMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final azureextensionmodule.proxies.System_AuthorizedDate that = (azureextensionmodule.proxies.System_AuthorizedDate) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
